package org.gradle.plugins.ide;

import org.gradle.api.Describable;
import org.gradle.api.file.FileSystemLocation;
import org.gradle.api.provider.Provider;

/**
 * Represents an IDE "workspace" that is generated by Gradle and can be opened in the IDE.
 *
 * @since 4.7
 */
public interface IdeWorkspace extends Describable {
    /**
     * Returns the location of the generated workspace.
     */
    Provider<? extends FileSystemLocation> getLocation();
}
