package dev.ide.ui.editor.preview

import androidx.compose.ui.geometry.Offset
import androidx.compose.ui.geometry.Size
import androidx.compose.ui.graphics.Canvas
import androidx.compose.ui.graphics.ImageBitmap
import androidx.compose.ui.graphics.drawscope.CanvasDrawScope
import androidx.compose.ui.unit.Density
import androidx.compose.ui.unit.LayoutDirection
import dev.ide.ui.backend.UiDrawable
import dev.ide.ui.backend.UiProjectIcon

/**
 * A project's launcher icon as an image file's bytes, rendering the XML one when that is all it has.
 *
 * Most Android projects have no raster launcher icon at all: the default templates ship a vector adaptive
 * icon, and so does anything generated by Android Studio's asset wizard. Taking only a raster therefore
 * means taking nothing from most projects, which is how a store listing ends up drawing the generic glyph
 * tile for a project that plainly has an icon.
 *
 * Rendering one needs a canvas, so this lives with the UI rather than in the engine, next to the app-icon
 * studio's rasteriser and using the same adaptive-icon geometry.
 */
object ProjectIconRaster {

    /** What a published store listing gets. Large enough for the hero tile, small enough to stay well under
     *  the media bucket's 2 MB limit. */
    const val STORE_PIXELS = 512

    /**
     * [icon] as image bytes, or null when it cannot be rendered.
     *
     * A raster icon is passed through as the file's own bytes: it is already the image the launcher draws,
     * and re-encoding it would only lose to its own compression. A drawable is rendered at [pixels].
     *
     * [loadImage] reads an image file the drawable references, by absolute path. An adaptive icon's
     * foreground is very often a `<bitmap>`, so without it the common case renders as an empty box.
     */
    suspend fun toBytes(
        icon: UiProjectIcon,
        pixels: Int = STORE_PIXELS,
        loadImage: suspend (String) -> ByteArray?,
    ): ByteArray? = when (icon) {
        is UiProjectIcon.Raster -> icon.bytes.takeIf { it.isNotEmpty() }
        is UiProjectIcon.Drawable -> renderPng(icon.drawable, pixels, loadImage)
    }

    /** [drawable] rendered to a square PNG, with every image it references resolved first. */
    suspend fun renderPng(
        drawable: UiDrawable,
        pixels: Int = STORE_PIXELS,
        loadImage: suspend (String) -> ByteArray?,
    ): ByteArray? {
        if (pixels <= 0) return null
        val images = decodeReferencedImages(drawable, loadImage)
        return render(drawable, pixels, images)?.let(::encodeImagePng)
    }

    /**
     * Draw [drawable] into a [pixels]-square bitmap, resolving bitmap layers through [images] (keyed by the
     * file path the drawable referenced).
     *
     * An adaptive icon is drawn the way a launcher draws it: its layers are authored in a 108-unit box of
     * which only the central 72 are guaranteed visible, so the box is scaled up and centred. Anything else
     * fills the square, because a plain vector or layer-list has no safe zone to honour and scaling it up
     * would just crop it.
     *
     * No mask: the tile that shows the icon does its own clipping, and a shape burned into the image would
     * be the wrong one wherever that tile is not a squircle.
     */
    fun render(drawable: UiDrawable, pixels: Int, images: Map<String, ImageBitmap> = emptyMap()): ImageBitmap? {
        if (pixels <= 0) return null
        val adaptive = (drawable as? UiDrawable.Layers)?.adaptive == true
        return runCatching {
            val bitmap = ImageBitmap(pixels, pixels)
            val edge = pixels.toFloat()
            val canvasSize = Size(edge, edge)
            val boxEdge = if (adaptive) edge * AppIconRaster.BOX_TO_SAFE_ZONE else edge
            val inset = (edge - boxEdge) / 2f
            CanvasDrawScope().draw(Density(1f), LayoutDirection.Ltr, Canvas(bitmap), canvasSize) {
                drawUiDrawable(drawable, Offset(inset, inset), Size(boxEdge, boxEdge)) { ref ->
                    ref.filePath?.let(images::get)
                }
            }
            bitmap
        }.getOrNull()
    }

    /** Every image file [drawable] references, decoded. Unreadable ones are left out and draw as nothing. */
    private suspend fun decodeReferencedImages(
        drawable: UiDrawable,
        loadImage: suspend (String) -> ByteArray?,
    ): Map<String, ImageBitmap> {
        val paths = LinkedHashSet<String>()
        collectImagePaths(drawable, paths)
        val out = LinkedHashMap<String, ImageBitmap>(paths.size)
        for (path in paths) {
            val bytes = runCatching { loadImage(path) }.getOrNull() ?: continue
            val image = runCatching { decodeImageBytes(bytes) }.getOrNull() ?: continue
            out[path] = image
        }
        return out
    }

    private fun collectImagePaths(d: UiDrawable, out: MutableSet<String>) {
        when (d) {
            is UiDrawable.Bitmap -> d.filePath?.let(out::add)
            is UiDrawable.Layers -> d.layers.forEach { collectImagePaths(it.drawable, out) }
            is UiDrawable.States -> {
                d.states.forEach { collectImagePaths(it.drawable, out) }
                d.defaultLayer?.let { collectImagePaths(it, out) }
            }
            else -> Unit
        }
    }
}
