// Copyright (C) 2026 tyron12233
// SPDX-License-Identifier: GPL-3.0-or-later WITH Classpath-exception-2.0
// See LICENSE-EXCEPTION: a plugin linking against this file may use any license.
package dev.ide.android

import android.content.Context
import android.security.keystore.KeyGenParameterSpec
import android.security.keystore.KeyProperties
import android.util.Base64
import dev.ide.platform.log.Log
import dev.ide.store.impl.StoreTokenStore
import java.security.KeyStore
import javax.crypto.Cipher
import javax.crypto.KeyGenerator
import javax.crypto.SecretKey
import javax.crypto.spec.GCMParameterSpec

/**
 * Where the store's sign-in survives a restart: the refresh token, encrypted, in the app's own preferences.
 *
 * Without this the session lived in memory only, so every launch presented a signed-out store and the user
 * signed in with GitHub again — the account port has restored a session from a stored token all along, and
 * the Android host simply never handed it anywhere to store one.
 *
 * The token is a credential, so it is sealed with an AES-GCM key held in the **Android Keystore**: the key
 * material never leaves the keystore, and a copy of the preferences file taken off a device (a backup, an
 * `adb` pull on an unlocked developer build) is ciphertext without it. Not `EncryptedSharedPreferences`,
 * which would add a dependency whose keyset handling is a known source of unrecoverable crashes on exactly
 * the long tail of ROMs this app runs on.
 *
 * **A keystore that will not cooperate means no persistence, never plaintext.** Some devices fail to
 * generate or load a key at all, and on those the sign-in behaves as it did before this existed rather than
 * quietly writing a bearer credential to disk. The failure is logged once per call site, not surfaced: a
 * user who has to sign in again is a smaller problem than a dialog nobody can act on.
 */
class AndroidTokenStore(context: Context) : StoreTokenStore {

    private val prefs = context.applicationContext.getSharedPreferences(PREFS, Context.MODE_PRIVATE)
    private val log = Log.logger("ide.store.auth")

    override fun read(): String? {
        val stored = prefs.getString(KEY_TOKEN, null)?.takeIf { it.isNotBlank() } ?: return null
        val key = secretKey() ?: return null
        return runCatching {
            val raw = Base64.decode(stored, Base64.NO_WRAP)
            // The IV is written in front of the ciphertext: GCM needs a fresh one per encryption, so it is
            // generated by the cipher and carried with the value rather than fixed anywhere.
            require(raw.size > IV_BYTES) { "stored token is too short to carry an IV" }
            val cipher = Cipher.getInstance(TRANSFORMATION)
            cipher.init(Cipher.DECRYPT_MODE, key, GCMParameterSpec(TAG_BITS, raw, 0, IV_BYTES))
            String(cipher.doFinal(raw, IV_BYTES, raw.size - IV_BYTES), Charsets.UTF_8)
        }.getOrElse {
            // A token that cannot be decrypted is a token that cannot be used: drop it so every later read
            // is not another failed decrypt. This is what a reinstall or a reset keystore looks like.
            log.warn("Stored sign-in could not be read (${it.javaClass.simpleName}); signing out locally")
            prefs.edit().remove(KEY_TOKEN).apply()
            null
        }
    }

    override fun write(refreshToken: String?) {
        if (refreshToken.isNullOrBlank()) {
            prefs.edit().remove(KEY_TOKEN).apply()
            return
        }
        val key = secretKey() ?: return
        runCatching {
            val cipher = Cipher.getInstance(TRANSFORMATION)
            cipher.init(Cipher.ENCRYPT_MODE, key)
            val sealed = cipher.doFinal(refreshToken.toByteArray(Charsets.UTF_8))
            val out = ByteArray(cipher.iv.size + sealed.size)
            cipher.iv.copyInto(out)
            sealed.copyInto(out, cipher.iv.size)
            prefs.edit().putString(KEY_TOKEN, Base64.encodeToString(out, Base64.NO_WRAP)).apply()
        }.onFailure {
            log.warn("Sign-in could not be saved (${it.javaClass.simpleName}); it will not survive a restart")
        }
    }

    /**
     * The app's AES key from the Android Keystore, generated on first use, or null when the device will not
     * provide one.
     *
     * Not tied to device unlock ([KeyGenParameterSpec.Builder.setUserAuthenticationRequired] is left off):
     * the session is restored during startup, which can happen on a locked device after a reboot, and a key
     * that refuses to decrypt then would present a signed-out store for reasons the user cannot see.
     */
    private fun secretKey(): SecretKey? = runCatching {
        val store = KeyStore.getInstance(ANDROID_KEYSTORE).apply { load(null) }
        (store.getKey(KEY_ALIAS, null) as? SecretKey) ?: generateKey()
    }.getOrElse {
        log.warn("The device keystore is unavailable (${it.javaClass.simpleName}); the sign-in stays in memory")
        null
    }

    private fun generateKey(): SecretKey =
        KeyGenerator.getInstance(KeyProperties.KEY_ALGORITHM_AES, ANDROID_KEYSTORE).apply {
            init(
                KeyGenParameterSpec.Builder(
                    KEY_ALIAS,
                    KeyProperties.PURPOSE_ENCRYPT or KeyProperties.PURPOSE_DECRYPT,
                )
                    .setBlockModes(KeyProperties.BLOCK_MODE_GCM)
                    .setEncryptionPaddings(KeyProperties.ENCRYPTION_PADDING_NONE)
                    .build(),
            )
        }.generateKey()

    private companion object {
        const val PREFS = "codeassist.store.auth"
        const val KEY_TOKEN = "refresh_token"
        const val ANDROID_KEYSTORE = "AndroidKeyStore"
        const val KEY_ALIAS = "codeassist.store.auth"
        const val TRANSFORMATION = "AES/GCM/NoPadding"

        /** GCM's standard 96-bit IV and 128-bit tag: what the platform cipher produces by default. */
        const val IV_BYTES = 12
        const val TAG_BITS = 128
    }
}
