package dev.ide.android

import com.android.tools.r8.D8
import com.android.tools.r8.D8Command
import com.android.tools.r8.OutputMode
import dalvik.system.InMemoryDexClassLoader
import dev.ide.jvm.AsmPeerFactory
import java.nio.ByteBuffer
import java.nio.file.Files
import java.nio.file.Path
import java.security.MessageDigest
import java.util.concurrent.ConcurrentHashMap
import java.util.concurrent.atomic.AtomicLong

/**
 * A peer factory for ART: reuses [AsmPeerFactory]'s class-file generation but converts the generated bytes to
 * dex with the bundled in-process D8 before loading them (ART's class loaders reject class-file bytecode).
 * The generated trampolines use no language feature that needs desugaring, so D8 runs without a library or
 * classpath.
 *
 * **Dex cache.** D8 costs ~25ms per peer, and a single Material3 composable needs ~20 distinct peers (~0.5s the
 * first time a preview composes). [AsmPeerFactory] caches the loaded [Class] per factory, but a preview rebuilds
 * its executor (hence a fresh factory) on every file/path switch — so without a cross-factory cache each reopen
 * re-dexes the same peers. Peer bytes are deterministic, and most shapes (Function proxies, Compose Node
 * subclasses) recur across files/projects, so a PROCESS-WIDE cache keyed by the input-bytes hash skips D8 on
 * every render after the first: a `<sha>.dex` file (optionally persisted to [diskCacheDir], surviving app
 * restarts) is loaded straight into an [InMemoryDexClassLoader]. Correctness is unchanged — same input bytes
 * dex to the same output.
 */
class DexPeerFactory(
    private val diskCacheDir: Path? = null,
    proxyExceptionSink: ((Throwable) -> Unit)? = null,
) : AsmPeerFactory(proxyExceptionSink = proxyExceptionSink) {

    override fun define(binaryName: String, bytes: ByteArray): Class<*> {
        val dex = dexFor(binaryName, bytes)
        return InMemoryDexClassLoader(ByteBuffer.wrap(dex), javaClass.classLoader).loadClass(binaryName)
    }

    /** The dex bytes for a peer's class bytes: a process-memory hit, then a disk hit, else D8 (and populate both). */
    private fun dexFor(binaryName: String, classBytes: ByteArray): ByteArray {
        val key = sha256(classBytes)
        memCache[key]?.let { return it }
        val onDisk = diskCacheDir?.resolve("$key.dex")
        if (onDisk != null && Files.isRegularFile(onDisk)) {
            return runCatching { Files.readAllBytes(onDisk) }.getOrNull()?.also { memCache[key] = it } ?: dexAndCache(binaryName, classBytes, key, onDisk)
        }
        return dexAndCache(binaryName, classBytes, key, onDisk)
    }

    private fun dexAndCache(binaryName: String, classBytes: ByteArray, key: String, onDisk: Path?): ByteArray {
        val dir = Files.createTempDirectory("vm-peer")
        val t0 = System.nanoTime()
        try {
            dexedNames.add(binaryName)
            Files.write(dir.resolve("Peer.class"), classBytes)
            D8.run(
                D8Command.builder()
                    .addProgramFiles(dir.resolve("Peer.class"))
                    .setMinApiLevel(26)
                    .setDisableDesugaring(true)
                    .setOutput(dir, OutputMode.DexIndexed)
                    .build(),
            )
            val dex = Files.readAllBytes(dir.resolve("classes.dex"))
            memCache[key] = dex
            if (onDisk != null) runCatching {
                Files.createDirectories(onDisk.parent)
                Files.write(onDisk, dex)
            }
            return dex
        } finally {
            dexNanos.addAndGet(System.nanoTime() - t0)
            dexCount.incrementAndGet()
            dir.toFile().deleteRecursively()
        }
    }

    private fun sha256(bytes: ByteArray): String =
        MessageDigest.getInstance("SHA-256").digest(bytes).joinToString("") { "%02x".format(it) }

    companion object {
        /** Process-wide peer-dex cache (input-bytes SHA → dex bytes), so a rebuilt executor/factory reuses
         *  earlier dex output instead of re-running D8. Bounded only by the finite set of peer shapes. */
        private val memCache = ConcurrentHashMap<String, ByteArray>()

        /** Cold-path profiling: total time + count of ACTUAL D8 dexing (cache hits don't count). */
        val dexNanos = AtomicLong(0)
        val dexCount = AtomicLong(0)
        /** Diagnostic: the binary names actually D8-dexed since the last [reset] (cache misses only). */
        val dexedNames = java.util.concurrent.CopyOnWriteArrayList<String>()
        fun reset() { dexNanos.set(0); dexCount.set(0); dexedNames.clear() }
        fun snapshot(): String = "peer-dex: ${dexCount.get()} peers, ${dexNanos.get() / 1_000_000}ms (cached shapes: ${memCache.size})"

        /** Test seam: clear the process-wide cache so a "cold" measurement re-dexes from scratch. */
        fun clearCache() { memCache.clear() }
    }
}
