package dev.ide.kotlin.syntax

import com.intellij.lang.ASTNode
import com.intellij.psi.impl.source.tree.LeafElement
import org.jetbrains.kotlin.kmp.tree.LightNode
import org.jetbrains.kotlin.kmp.tree.LightSyntaxTree
import com.intellij.psi.PsiFile
import dev.ide.psi.IntellijPsiHost
import java.io.File
import kotlin.test.Test
import kotlin.test.assertTrue
import org.jetbrains.kotlin.idea.KotlinLanguage

/**
 * Parser parity: the vendored multiplatform grammar against the compiler's own PSI parser, over the Kotlin
 * compiler's parser corpus.
 *
 * This is the suite the whole module is for. The corpus is `compiler/psi/psi-impl/testData` copied from the
 * Kotlin repository (774 files), which is not ordinary code: it is the cases the Kotlin team wrote to pin
 * their parser down, including every error-recovery path they cared about. Agreeing with ordinary code is
 * easy; this is the hard half.
 *
 * **Expectations come from OUR pinned compiler, not from the vendored `.txt` dumps.** Those dumps were
 * generated by whatever Kotlin revision committed them, while this build pins `2.4.20-dev-6138`, so a
 * comparison against them would report version skew as parser error. Diffing against the live PSI keeps the
 * question honest: does this tree match the parser this IDE ships today?
 *
 * **Divergences are tracked in a baseline, not ignored.** `baselines/parser-parity.txt` lists the files known
 * to differ. A file that diverges and is NOT listed fails the suite; a listed file that starts passing also
 * fails, with instructions, so the list can only shrink. That turns "100% parity" from an aspiration into a
 * number that cannot silently regress.
 */
class KotlinParserParityTest {

    @Test
    fun theVendoredGrammarAgreesWithTheCompiler() {
        val corpus = corpusRoot()
        val files = corpus.walkTopDown()
            .filter { it.isFile && (it.extension == "kt" || it.extension == "kts") }
            .sortedBy { it.path }
            .toList()
        assertTrue(files.size > 500, "expected the vendored corpus, found ${files.size} files under $corpus")

        val baseline = readBaseline()
        val diverged = LinkedHashMap<String, String>()
        val clusters = HashMap<String, Int>()
        val samples = HashMap<String, Triple<String, String, String>>()
        var crashed = 0

        for (file in files) {
            val relative = file.relativeTo(corpus).path.replace(File.separatorChar, '/')
            // The harness upstream normalizes line endings before comparing; so do we, or every CRLF file
            // reads as an offset difference.
            val text = file.readText().replace("\r\n", "\n")
            val isScript = file.extension == "kts"

            val ours = runCatching { ourRender(KotlinSyntax.parse(text, isScript)) }
                .getOrElse { "<threw: ${it::class.simpleName}: ${it.message}>" }
            val theirs = runCatching { psiRender(relative, text) }
                .getOrElse { "<threw: ${it::class.simpleName}: ${it.message}>" }

            if (ours.startsWith("<threw")) crashed++
            if (ours != theirs) {
                diverged[relative] = firstDifference(theirs, ours)
                val kind = differenceKind(theirs, ours)
                clusters.merge(kind, 1, Int::plus)
                samples.putIfAbsent(kind, Triple(relative, theirs, ours))
            }
        }

        // `-DkotlinSyntax.updateBaseline=true` rewrites the list, matching the repo's regression-baseline
        // convention. Never run it to "fix" a red suite without reading the diff first: the whole point of
        // the file is that a divergence has to be looked at once before it stops being news.
        if (System.getProperty("kotlinSyntax.updateBaseline") == "true") {
            writeBaseline(diverged.keys, clusters)
            println("baseline rewritten with ${diverged.size} entries")
            return
        }

        val unexpectedFailures = diverged.keys - baseline
        val unexpectedPasses = baseline - diverged.keys

        val agreed = files.size - diverged.size
        println(
            "parser parity: $agreed/${files.size} files agree with the compiler " +
                "(${"%.2f".format(agreed * 100.0 / files.size)}%), ${diverged.size} diverge, $crashed threw",
        )

        if (clusters.isNotEmpty()) {
            println("divergence kinds, most common first:")
            clusters.entries.sortedByDescending { it.value }.take(20)
                .forEach { (kind, count) ->
                    println("  %5d  %s".format(count, kind))
                    samples[kind]?.let { (name, expected, actual) ->
                        val at = expected.commonPrefixWith(actual).length
                        val from = maxOf(0, at - 160)
                        println("           in $name")
                        println("           compiler: …" + expected.substring(from, minOf(expected.length, at + 120)))
                        println("           ours:     …" + actual.substring(from, minOf(actual.length, at + 120)))
                    }
                }
        }

        if (unexpectedPasses.isNotEmpty()) {
            fail(
                "${unexpectedPasses.size} baselined file(s) now AGREE with the compiler. That is good news: " +
                    "remove them from baselines/parser-parity.txt so the list keeps shrinking.\n  " +
                    unexpectedPasses.sorted().joinToString("\n  "),
            )
        }
        if (unexpectedFailures.isNotEmpty()) {
            val shown = unexpectedFailures.sorted().take(10)
            fail(
                "${unexpectedFailures.size} file(s) diverge from the compiler and are not baselined:\n\n" +
                    shown.joinToString("\n\n") { "$it\n${diverged[it]}" },
            )
        }
    }

    /**
     * The same comparison over THIS repository's own Kotlin sources.
     *
     * The compiler's corpus is adversarial by design; this is the other half of the question — does the
     * vendored grammar agree with the parser the IDE ships, on the ordinary code it will actually be asked
     * to parse? Roughly 2,400 files, none written with this test in mind.
     */
    @Test
    fun theVendoredGrammarAgreesOnThisRepositorysOwnSources() {
        val root = File(System.getProperty("kotlinSyntax.corpusRoot")!!)
        val files = root.walkTopDown()
            .onEnter { it.name !in SKIPPED_DIRECTORIES && !it.name.startsWith(".") }
            .filter { it.isFile && it.extension == "kt" }
            .sortedBy { it.path }
            .toList()
        assertTrue(files.size > 1000, "expected the repository's sources, found ${files.size}")

        val diverged = ArrayList<String>()
        for (file in files) {
            val text = file.readText().replace("\r\n", "\n")
            val relative = file.relativeTo(root).path.replace(File.separatorChar, '/')
            val ours = runCatching { ourRender(KotlinSyntax.parse(text)) }
                .getOrElse { "<threw: ${it::class.simpleName}: ${it.message}>" }
            val theirs = runCatching { psiRender(relative, text) }
                .getOrElse { "<threw: ${it::class.simpleName}: ${it.message}>" }
            if (ours != theirs) diverged += "$relative\n${firstDifference(theirs, ours)}"
        }

        println("repository sweep: ${files.size - diverged.size}/${files.size} files agree with the compiler")
        assertTrue(
            diverged.isEmpty(),
            "the vendored grammar diverges on ${diverged.size} of this repo's own files:\n\n" +
                diverged.take(5).joinToString("\n"),
        )
    }

    /**
     * Our tree, rendered under the shared vocabulary. Deliberately NOT the module's own `render`: both sides
     * have to agree on what an element is CALLED before a difference means anything, and that mapping is
     * test-only knowledge.
     */
    private fun ourRender(tree: LightSyntaxTree): String {
        val out = StringBuilder()
        appendOurs(tree, tree.getRoot(), out)
        return normalizeRoot(out.toString())
    }

    private fun appendOurs(tree: LightSyntaxTree, node: LightNode, out: StringBuilder) {
        val name = ElementNames.of(tree.getType(node))
        if (tree.isToken(node)) {
            out.append(name)
            return
        }
        // A COLLAPSED marker is semantically one token, and the light tree still records it as a composite
        // wrapping the tokens it covers. PSI's `collapse` produces a leaf outright, so flattening here
        // compares grammar rather than the two libraries' idea of what a collapsed marker is.
        //
        // It is not only the one-token case: the parser collapses every modifier keyword this way, and also
        // the operators the new lexer leaves in pieces — `!!` is `(EXCLEXCL EXCL EXCL)` here and one EXCLEXCL
        // token to PSI, and likewise `?:` and `?.`. The test is therefore "a composite named after a TOKEN
        // kind, holding only tokens", which is exactly what a collapse produces and nothing else is.
        val children = tree.getChildren(node)
        if (ElementNames.isTokenKind(tree.getType(node)) && children.isNotEmpty() &&
            children.all { tree.isToken(it) }
        ) {
            out.append(name)
            return
        }
        out.append('(').append(name)
        for (child in children) {
            if (isTrivia(ElementNames.of(tree.getType(child)))) continue
            out.append(' ')
            appendOurs(tree, child, out)
        }
        out.append(')')
    }

    /** The compiler's PSI tree, rendered the same way. */
    private fun psiRender(name: String, text: String): String {
        val fileName = name.substringAfterLast('/')
        val psi: PsiFile = IntellijPsiHost.parse(fileName, KotlinLanguage.INSTANCE, text)
        // PSI parses blocks and lambdas lazily and expands them later, which shows up as a tree difference on
        // erroneous input that is not a parser difference at all. Force it whole before looking.
        IntellijPsiHost.forceFullParse(psi)
        val out = StringBuilder()
        appendPsi(psi.node, out)
        return normalizeRoot(out.toString())
    }

    private fun appendPsi(node: ASTNode, out: StringBuilder) {
        // Leaf-ness is `LeafElement`, not "has no children": an EMPTY composite (the package directive of a
        // file that declares no package, say) also has none, and rendering it as a token rather than as `()`
        // made every single file in the corpus look like a divergence.
        if (node is LeafElement) {
            out.append(ElementNames.of(node.elementType))
            return
        }
        out.append('(').append(ElementNames.of(node.elementType))
        for (child in node.getChildren(null)) {
            if (isTrivia(ElementNames.of(child.elementType))) continue
            out.append(' ')
            appendPsi(child, out)
        }
        out.append(')')
    }

    /**
     * Both renderings start with their own name for the file element, and that is not a grammar difference:
     * PSI names it after the file type while the light tree uses its synthetic root. Normalize the opening
     * token of each so the comparison is about everything else.
     */
    private fun normalizeRoot(rendered: String): String =
        rendered.replaceFirst(Regex("^\\((kotlin\\.FILE|kotlin\\.SCRIPT|FILE)"), "(FILE")

    private fun isTrivia(typeName: String): Boolean =
        typeName == "WHITE_SPACE" || typeName.endsWith("COMMENT") || typeName == "KDoc"

    /**
     * A compact key for what KIND of difference this is: the first atom that differs on each side. Grouping
     * by it turns 600 individual failures into the handful of root causes they actually are.
     */
    private fun differenceKind(expected: String, actual: String): String {
        val at = expected.commonPrefixWith(actual).length
        return "${atomAt(expected, at)} != ${atomAt(actual, at)}"
    }

    private fun atomAt(rendered: String, at: Int): String {
        if (at >= rendered.length) return "<end>"
        var start = at
        while (start > 0 && rendered[start - 1] !in " ()") start--
        var end = at
        while (end < rendered.length && rendered[end] !in " ()") end++
        val atom = rendered.substring(start, end)
        return atom.ifEmpty { "'" + rendered[at] + "'" }
    }

    /** The first place two renderings differ, with context, so a failure is readable. */
    private fun firstDifference(expected: String, actual: String): String {
        val at = expected.commonPrefixWith(actual).length
        val from = maxOf(0, at - 60)
        return buildString {
            appendLine("  first differs at char $at")
            appendLine("  compiler: …${expected.substring(from, minOf(expected.length, at + 80))}")
            appendLine("  ours:     …${actual.substring(from, minOf(actual.length, at + 80))}")
        }
    }

    private fun corpusRoot(): File {
        val root = System.getProperty("kotlinSyntax.corpusRoot")?.let(::File)
            ?: error("kotlinSyntax.corpusRoot is not set; see the module's build.gradle.kts")
        return File(root, "experimental/kotlin-syntax/testData/kotlin-psi").also {
            assertTrue(it.isDirectory, "vendored corpus missing at $it")
        }
    }

    private fun readBaseline(): Set<String> {
        val file = File(
            System.getProperty("kotlinSyntax.corpusRoot")!!,
            "experimental/kotlin-syntax/baselines/parser-parity.txt",
        )
        if (!file.isFile) return emptySet()
        return file.readLines()
            .map { it.substringBefore('#').trim() }
            .filter { it.isNotEmpty() }
            .toSet()
    }

    private fun writeBaseline(paths: Set<String>, clusters: Map<String, Int>) {
        val file = File(
            System.getProperty("kotlinSyntax.corpusRoot")!!,
            "experimental/kotlin-syntax/baselines/parser-parity.txt",
        )
        file.parentFile.mkdirs()
        file.writeText(
            buildString {
                appendLine("# Files where the vendored multiplatform grammar does not reproduce the PSI parser's tree.")
                appendLine("#")
                appendLine("# This list may only SHRINK. A file that diverges and is not listed here fails the suite;")
                appendLine("# a listed file that starts agreeing also fails, so the number cannot drift upward quietly.")
                appendLine("# Regenerate with -DkotlinSyntax.updateBaseline=true, after reading the diff.")
                appendLine("#")
                appendLine("# The residue is old-parser-versus-new-parser behaviour, not a port defect: these are two")
                appendLine("# implementations JetBrains ships side by side, and the new one is still converging.")
                appendLine("# Most of it is one thing — BAD_CHARACTER, where the two lexers disagree about exotic")
                appendLine("# whitespace and about what belongs inside an error element.")
                appendLine("#")
                appendLine("# Kinds seen when this file was written, most common first:")
                clusters.entries.sortedByDescending { it.value }
                    .forEach { (kind, count) -> appendLine("#   %5d  %s".format(count, kind)) }
                appendLine()
                paths.sorted().forEach { appendLine(it) }
            },
        )
    }

    private fun fail(message: String): Nothing = throw AssertionError(message)

    private companion object {
        /** `testData` is the vendored corpus, which the suite above already covers on its own terms. */
        val SKIPPED_DIRECTORIES =
            setOf("build", "node_modules", "out", "testData", "vendor", ".gradle", ".git", ".kotlin")
    }
}
