package dev.ide.core

import dev.ide.platform.log.Log
import java.nio.file.Files
import java.nio.file.Path
import java.nio.file.Paths
import java.nio.file.StandardCopyOption

/**
 * The compile-time `java.awt` / `javax.swing` API, extracted from this module's resources so a project can be
 * compiled against it.
 *
 * A Swing program has to compile against those names, and the platform the IDE compiles it against usually
 * does not have them: `android.jar` on device, and `android.jar` on the desktop too whenever an Android SDK is
 * installed, since [IdeServices.defaultDesktopSdk] prefers one. Appending this jar to the platform's classpath
 * closes that gap for both.
 *
 * The jar is generated by `:awt-toolkit` by running its own name remap backwards, so what a program compiles
 * against and the toolkit it runs on are the same classes and cannot drift. It is COMPILE-ONLY and must never
 * reach a class loader: nothing may define a class in `java.*`.
 */
object SwingApiStubs {

    private val log = Log.logger("ide.swing")
    private const val RESOURCE = "swing/swing-api-stubs.jar"

    @Volatile private var extracted: Path? = null

    /**
     * The bundled jar on disk, extracted once per process, or null when this build has no stubs bundled (the
     * caller then simply gets no Swing on the compile classpath, rather than a failure).
     *
     * It lands in the JVM's temp directory, which is the app's own cache directory on Android and needs no
     * project to exist: a platform SDK is built before any project is open. Re-extracting each process rather
     * than trusting a previous one's copy keeps it correct across an app upgrade for the price of a 100 KB
     * write at startup.
     */
    @Synchronized
    fun bundled(): Path? = extracted ?: extractTo(Paths.get(System.getProperty("java.io.tmpdir"), "codeassist-swing-api"))
        ?.also { extracted = it }

    /** Write the bundled jar into [cachesRoot], replacing whatever was there. */
    private fun extractTo(cachesRoot: Path): Path? {
        val target = cachesRoot.resolve("swing-api-stubs.jar")
        val stream = javaClass.classLoader.getResourceAsStream(RESOURCE) ?: run {
            log.warn("no bundled $RESOURCE; java.awt/javax.swing will not resolve for compilation")
            return null
        }
        return runCatching {
            Files.createDirectories(cachesRoot)
            // Write beside the target and move, so a half-written jar can never be picked up as complete.
            val partial = Files.createTempFile(cachesRoot, "swing-api", ".part")
            stream.use { input -> Files.newOutputStream(partial).use { input.copyTo(it) } }
            Files.move(partial, target, StandardCopyOption.REPLACE_EXISTING)
            target
        }.getOrElse {
            log.warn("could not extract $RESOURCE", it)
            null
        }
    }
}
