version = 2

[module]
type = "java-lib"
name = "vcs-ui"
languageLevel = "JAVA_17"
output = "build/codeassist/classes"

[sourceSets.commonMain]
scope = "IMPLEMENTATION"
java = ["src/commonMain/kotlin"]

[sourceSets.composeResources]
scope = "IMPLEMENTATION"
java = ["build/compose-resources/kotlin"]
resources = ["build/compose-resources/resources"]

[dependencies]
implementation = [{ module = "ide-ui" }, "org.jetbrains.compose.runtime:runtime:1.11.1", "org.jetbrains.compose.foundation:foundation:1.11.1", "org.jetbrains.compose.material3:material3:1.9.0", "org.jetbrains.compose.ui:ui:1.11.1", "org.jetbrains.compose.components:components-resources:1.11.1", "org.jetbrains.kotlinx:kotlinx-coroutines-core:1.11.0", "kotlin-stdlib"]

[composeResources]
package = "dev.ide.vcs.ui.generated.resources"
roots = ["src/commonMain/composeResources"]

[kotlin]
commonSourceRoots = ["src/commonMain/kotlin"]
