// Generated by run/jvm-vm/tools/skia_call_shapes.py from skiko-awt's native method descriptors.
// Regenerate after a skiko upgrade; a shape missing here is reported as unsupported at bind time.
@file:OptIn(kotlinx.cinterop.ExperimentalForeignApi::class)

package dev.ide.vm.skiko

import kotlinx.cinterop.CFunction
import kotlinx.cinterop.COpaquePointer
import kotlinx.cinterop.invoke
import kotlinx.cinterop.reinterpret

/** Shape key (`JFF>V`: parameters, then the return) to the index [callSkia] dispatches on. */
internal val skiaShapes: Map<String, Int> = mapOf(
    ">F" to 0,
    ">I" to 1,
    ">J" to 2,
    ">V" to 3,
    "F>J" to 4,
    "FFFF>J" to 5,
    "FFFFFFFFI>I" to 6,
    "FFFFFFFFIFFFJJ>J" to 7,
    "FFFFFFFFIFFJJ>J" to 8,
    "FFFFFFFFJ>J" to 9,
    "FFFFFFFIJ>I" to 10,
    "FFFFFFI>I" to 11,
    "FFFFFFI>J" to 12,
    "FFFFFFIIJJ>J" to 13,
    "FFFFFFJJIIIJ>J" to 14,
    "FFFFFFJJJIIIJ>J" to 15,
    "FFFFI>I" to 16,
    "FFFFI>J" to 17,
    "FFFFII>J" to 18,
    "FFFFIII>J" to 19,
    "FFFFIJJ>J" to 20,
    "FFFFIJJJ>J" to 21,
    "FFFFJ>J" to 22,
    "FFFFJI>J" to 23,
    "FFFFJJIIIJ>J" to 24,
    "FFFFJJJIIIJ>J" to 25,
    "FFFI>J" to 26,
    "FFFIFFFJJ>J" to 27,
    "FFFIFFJJ>J" to 28,
    "FFFJJIIIJ>J" to 29,
    "FFFJJJIIIJ>J" to 30,
    "FFI>J" to 31,
    "FFIFII>J" to 32,
    "FFIJJ>J" to 33,
    "FFJJ>J" to 34,
    "FJ>J" to 35,
    "FJJ>J" to 36,
    "I>I" to 37,
    "I>J" to 38,
    "I>V" to 39,
    "IFI>J" to 40,
    "II>I" to 41,
    "II>J" to 42,
    "IIF>J" to 43,
    "IIFJJJ>J" to 44,
    "III>J" to 45,
    "IIIIII>J" to 46,
    "IIIIJIJ>J" to 47,
    "IIIIJJI>J" to 48,
    "IIIIJJIJ>J" to 49,
    "IIJ>J" to 50,
    "IIJFFIIIIJJ>J" to 51,
    "IIJIII>J" to 52,
    "IJ>J" to 53,
    "IJJ>J" to 54,
    "IJJJ>J" to 55,
    "J>F" to 56,
    "J>I" to 57,
    "J>J" to 58,
    "J>V" to 59,
    "JF>I" to 60,
    "JF>J" to 61,
    "JF>V" to 62,
    "JFF>I" to 63,
    "JFF>J" to 64,
    "JFF>V" to 65,
    "JFFF>J" to 66,
    "JFFF>V" to 67,
    "JFFFF>I" to 68,
    "JFFFF>J" to 69,
    "JFFFF>V" to 70,
    "JFFFFF>V" to 71,
    "JFFFFFF>V" to 72,
    "JFFFFFFFFII>J" to 73,
    "JFFFFFFI>V" to 74,
    "JFFFFFFIJ>V" to 75,
    "JFFFFII>J" to 76,
    "JFFFFII>V" to 77,
    "JFFFFJ>I" to 78,
    "JFFFFJ>J" to 79,
    "JFFFFJ>V" to 80,
    "JFFFFJIFFFFJIJ>V" to 81,
    "JFFFFJIII>V" to 82,
    "JFFFFJIJ>V" to 83,
    "JFFFFJJJI>I" to 84,
    "JFFFI>V" to 85,
    "JFFFIIFF>V" to 86,
    "JFFFJ>V" to 87,
    "JFFI>J" to 88,
    "JFFIIF>V" to 89,
    "JFFJ>I" to 90,
    "JFFJ>V" to 91,
    "JFFJI>I" to 92,
    "JFFJJ>V" to 93,
    "JFI>V" to 94,
    "JFIIJ>I" to 95,
    "JFJ>I" to 96,
    "JFJ>V" to 97,
    "JI>F" to 98,
    "JI>I" to 99,
    "JI>J" to 100,
    "JI>V" to 101,
    "JIF>J" to 102,
    "JIF>V" to 103,
    "JIFFD>V" to 104,
    "JII>F" to 105,
    "JII>I" to 106,
    "JII>J" to 107,
    "JII>V" to 108,
    "JIIFJ>V" to 109,
    "JIII>V" to 110,
    "JIIII>I" to 111,
    "JIIII>J" to 112,
    "JIIII>V" to 113,
    "JIIIII>I" to 114,
    "JIIIII>V" to 115,
    "JIIIIIIF>V" to 116,
    "JIIIIIJIIJI>J" to 117,
    "JIIIIJ>J" to 118,
    "JIIIIJI>I" to 119,
    "JIIIIJIIIJ>I" to 120,
    "JIIIIJJI>I" to 121,
    "JIIIIJJI>V" to 122,
    "JIIIIJJII>I" to 123,
    "JIIIIJJIII>I" to 124,
    "JIIIJIFFFF>J" to 125,
    "JIIJ>J" to 126,
    "JIIJ>V" to 127,
    "JIIJJ>J" to 128,
    "JIIJJ>V" to 129,
    "JIIJJJIJIJ>V" to 130,
    "JIJ>I" to 131,
    "JIJ>J" to 132,
    "JIJ>V" to 133,
    "JIJFJ>J" to 134,
    "JIJIJIII>J" to 135,
    "JIJJ>J" to 136,
    "JIJJ>V" to 137,
    "JIJJJJ>V" to 138,
    "JJ>D" to 139,
    "JJ>I" to 140,
    "JJ>J" to 141,
    "JJ>V" to 142,
    "JJF>J" to 143,
    "JJF>V" to 144,
    "JJFF>V" to 145,
    "JJFFF>V" to 146,
    "JJFFFF>V" to 147,
    "JJFFFFFFFFIIJI>V" to 148,
    "JJFFFFFFFIII>V" to 149,
    "JJFFFFI>V" to 150,
    "JJFFFFJ>J" to 151,
    "JJFFFFJ>V" to 152,
    "JJFFI>V" to 153,
    "JJFFIIJ>V" to 154,
    "JJFFJ>V" to 155,
    "JJFFJJ>V" to 156,
    "JJFIJ>V" to 157,
    "JJI>I" to 158,
    "JJI>J" to 159,
    "JJI>V" to 160,
    "JJIFFJ>V" to 161,
    "JJII>I" to 162,
    "JJII>J" to 163,
    "JJII>V" to 164,
    "JJIII>I" to 165,
    "JJIII>V" to 166,
    "JJIIII>I" to 167,
    "JJIIII>V" to 168,
    "JJIIIIFFFFIJ>V" to 169,
    "JJIIIII>I" to 170,
    "JJIIIJJ>J" to 171,
    "JJIIJI>J" to 172,
    "JJIIJJ>J" to 173,
    "JJIJ>F" to 174,
    "JJIJ>I" to 175,
    "JJIJ>J" to 176,
    "JJIJ>V" to 177,
    "JJIJII>J" to 178,
    "JJIJJ>V" to 179,
    "JJJ>I" to 180,
    "JJJ>J" to 181,
    "JJJ>V" to 182,
    "JJJI>I" to 183,
    "JJJI>J" to 184,
    "JJJI>V" to 185,
    "JJJIFFJ>V" to 186,
    "JJJIII>I" to 187,
    "JJJIJ>J" to 188,
    "JJJIJ>V" to 189,
    "JJJIJFJ>V" to 190,
    "JJJIJI>J" to 191,
    "JJJIJIFFF>J" to 192,
    "JJJIJJ>V" to 193,
    "JJJJ>I" to 194,
    "JJJJ>J" to 195,
    "JJJJ>V" to 196,
    "JJJJI>I" to 197,
    "JJJJIJ>V" to 198,
    "JJJJJJIJIFJ>V" to 199,
    "JJJJJJJ>V" to 200,
)

/** Calls [fn] as shape [shape] with [a] (each argument's raw bits) and returns the result's raw bits. */
internal fun callSkia(shape: Int, fn: COpaquePointer, a: LongArray): Long = when (shape) {
    0 -> fn.reinterpret<CFunction<() -> Float>>()().toRawBits().toLong()
    1 -> fn.reinterpret<CFunction<() -> Int>>()().toLong()
    2 -> fn.reinterpret<CFunction<() -> Long>>()()
    3 -> { fn.reinterpret<CFunction<() -> Unit>>()(); 0L }
    4 -> fn.reinterpret<CFunction<(Float) -> Long>>()(Float.fromBits(a[0].toInt()))
    5 -> fn.reinterpret<CFunction<(Float, Float, Float, Float) -> Long>>()(Float.fromBits(a[0].toInt()), Float.fromBits(a[1].toInt()), Float.fromBits(a[2].toInt()), Float.fromBits(a[3].toInt()))
    6 -> fn.reinterpret<CFunction<(Float, Float, Float, Float, Float, Float, Float, Float, Int) -> Int>>()(Float.fromBits(a[0].toInt()), Float.fromBits(a[1].toInt()), Float.fromBits(a[2].toInt()), Float.fromBits(a[3].toInt()), Float.fromBits(a[4].toInt()), Float.fromBits(a[5].toInt()), Float.fromBits(a[6].toInt()), Float.fromBits(a[7].toInt()), a[8].toInt()).toLong()
    7 -> fn.reinterpret<CFunction<(Float, Float, Float, Float, Float, Float, Float, Float, Int, Float, Float, Float, Long, Long) -> Long>>()(Float.fromBits(a[0].toInt()), Float.fromBits(a[1].toInt()), Float.fromBits(a[2].toInt()), Float.fromBits(a[3].toInt()), Float.fromBits(a[4].toInt()), Float.fromBits(a[5].toInt()), Float.fromBits(a[6].toInt()), Float.fromBits(a[7].toInt()), a[8].toInt(), Float.fromBits(a[9].toInt()), Float.fromBits(a[10].toInt()), Float.fromBits(a[11].toInt()), a[12], a[13])
    8 -> fn.reinterpret<CFunction<(Float, Float, Float, Float, Float, Float, Float, Float, Int, Float, Float, Long, Long) -> Long>>()(Float.fromBits(a[0].toInt()), Float.fromBits(a[1].toInt()), Float.fromBits(a[2].toInt()), Float.fromBits(a[3].toInt()), Float.fromBits(a[4].toInt()), Float.fromBits(a[5].toInt()), Float.fromBits(a[6].toInt()), Float.fromBits(a[7].toInt()), a[8].toInt(), Float.fromBits(a[9].toInt()), Float.fromBits(a[10].toInt()), a[11], a[12])
    9 -> fn.reinterpret<CFunction<(Float, Float, Float, Float, Float, Float, Float, Float, Long) -> Long>>()(Float.fromBits(a[0].toInt()), Float.fromBits(a[1].toInt()), Float.fromBits(a[2].toInt()), Float.fromBits(a[3].toInt()), Float.fromBits(a[4].toInt()), Float.fromBits(a[5].toInt()), Float.fromBits(a[6].toInt()), Float.fromBits(a[7].toInt()), a[8])
    10 -> fn.reinterpret<CFunction<(Float, Float, Float, Float, Float, Float, Float, Int, Long) -> Int>>()(Float.fromBits(a[0].toInt()), Float.fromBits(a[1].toInt()), Float.fromBits(a[2].toInt()), Float.fromBits(a[3].toInt()), Float.fromBits(a[4].toInt()), Float.fromBits(a[5].toInt()), Float.fromBits(a[6].toInt()), a[7].toInt(), a[8]).toLong()
    11 -> fn.reinterpret<CFunction<(Float, Float, Float, Float, Float, Float, Int) -> Int>>()(Float.fromBits(a[0].toInt()), Float.fromBits(a[1].toInt()), Float.fromBits(a[2].toInt()), Float.fromBits(a[3].toInt()), Float.fromBits(a[4].toInt()), Float.fromBits(a[5].toInt()), a[6].toInt()).toLong()
    12 -> fn.reinterpret<CFunction<(Float, Float, Float, Float, Float, Float, Int) -> Long>>()(Float.fromBits(a[0].toInt()), Float.fromBits(a[1].toInt()), Float.fromBits(a[2].toInt()), Float.fromBits(a[3].toInt()), Float.fromBits(a[4].toInt()), Float.fromBits(a[5].toInt()), a[6].toInt())
    13 -> fn.reinterpret<CFunction<(Float, Float, Float, Float, Float, Float, Int, Int, Long, Long) -> Long>>()(Float.fromBits(a[0].toInt()), Float.fromBits(a[1].toInt()), Float.fromBits(a[2].toInt()), Float.fromBits(a[3].toInt()), Float.fromBits(a[4].toInt()), Float.fromBits(a[5].toInt()), a[6].toInt(), a[7].toInt(), a[8], a[9])
    14 -> fn.reinterpret<CFunction<(Float, Float, Float, Float, Float, Float, Long, Long, Int, Int, Int, Long) -> Long>>()(Float.fromBits(a[0].toInt()), Float.fromBits(a[1].toInt()), Float.fromBits(a[2].toInt()), Float.fromBits(a[3].toInt()), Float.fromBits(a[4].toInt()), Float.fromBits(a[5].toInt()), a[6], a[7], a[8].toInt(), a[9].toInt(), a[10].toInt(), a[11])
    15 -> fn.reinterpret<CFunction<(Float, Float, Float, Float, Float, Float, Long, Long, Long, Int, Int, Int, Long) -> Long>>()(Float.fromBits(a[0].toInt()), Float.fromBits(a[1].toInt()), Float.fromBits(a[2].toInt()), Float.fromBits(a[3].toInt()), Float.fromBits(a[4].toInt()), Float.fromBits(a[5].toInt()), a[6], a[7], a[8], a[9].toInt(), a[10].toInt(), a[11].toInt(), a[12])
    16 -> fn.reinterpret<CFunction<(Float, Float, Float, Float, Int) -> Int>>()(Float.fromBits(a[0].toInt()), Float.fromBits(a[1].toInt()), Float.fromBits(a[2].toInt()), Float.fromBits(a[3].toInt()), a[4].toInt()).toLong()
    17 -> fn.reinterpret<CFunction<(Float, Float, Float, Float, Int) -> Long>>()(Float.fromBits(a[0].toInt()), Float.fromBits(a[1].toInt()), Float.fromBits(a[2].toInt()), Float.fromBits(a[3].toInt()), a[4].toInt())
    18 -> fn.reinterpret<CFunction<(Float, Float, Float, Float, Int, Int) -> Long>>()(Float.fromBits(a[0].toInt()), Float.fromBits(a[1].toInt()), Float.fromBits(a[2].toInt()), Float.fromBits(a[3].toInt()), a[4].toInt(), a[5].toInt())
    19 -> fn.reinterpret<CFunction<(Float, Float, Float, Float, Int, Int, Int) -> Long>>()(Float.fromBits(a[0].toInt()), Float.fromBits(a[1].toInt()), Float.fromBits(a[2].toInt()), Float.fromBits(a[3].toInt()), a[4].toInt(), a[5].toInt(), a[6].toInt())
    20 -> fn.reinterpret<CFunction<(Float, Float, Float, Float, Int, Long, Long) -> Long>>()(Float.fromBits(a[0].toInt()), Float.fromBits(a[1].toInt()), Float.fromBits(a[2].toInt()), Float.fromBits(a[3].toInt()), a[4].toInt(), a[5], a[6])
    21 -> fn.reinterpret<CFunction<(Float, Float, Float, Float, Int, Long, Long, Long) -> Long>>()(Float.fromBits(a[0].toInt()), Float.fromBits(a[1].toInt()), Float.fromBits(a[2].toInt()), Float.fromBits(a[3].toInt()), a[4].toInt(), a[5], a[6], a[7])
    22 -> fn.reinterpret<CFunction<(Float, Float, Float, Float, Long) -> Long>>()(Float.fromBits(a[0].toInt()), Float.fromBits(a[1].toInt()), Float.fromBits(a[2].toInt()), Float.fromBits(a[3].toInt()), a[4])
    23 -> fn.reinterpret<CFunction<(Float, Float, Float, Float, Long, Int) -> Long>>()(Float.fromBits(a[0].toInt()), Float.fromBits(a[1].toInt()), Float.fromBits(a[2].toInt()), Float.fromBits(a[3].toInt()), a[4], a[5].toInt())
    24 -> fn.reinterpret<CFunction<(Float, Float, Float, Float, Long, Long, Int, Int, Int, Long) -> Long>>()(Float.fromBits(a[0].toInt()), Float.fromBits(a[1].toInt()), Float.fromBits(a[2].toInt()), Float.fromBits(a[3].toInt()), a[4], a[5], a[6].toInt(), a[7].toInt(), a[8].toInt(), a[9])
    25 -> fn.reinterpret<CFunction<(Float, Float, Float, Float, Long, Long, Long, Int, Int, Int, Long) -> Long>>()(Float.fromBits(a[0].toInt()), Float.fromBits(a[1].toInt()), Float.fromBits(a[2].toInt()), Float.fromBits(a[3].toInt()), a[4], a[5], a[6], a[7].toInt(), a[8].toInt(), a[9].toInt(), a[10])
    26 -> fn.reinterpret<CFunction<(Float, Float, Float, Int) -> Long>>()(Float.fromBits(a[0].toInt()), Float.fromBits(a[1].toInt()), Float.fromBits(a[2].toInt()), a[3].toInt())
    27 -> fn.reinterpret<CFunction<(Float, Float, Float, Int, Float, Float, Float, Long, Long) -> Long>>()(Float.fromBits(a[0].toInt()), Float.fromBits(a[1].toInt()), Float.fromBits(a[2].toInt()), a[3].toInt(), Float.fromBits(a[4].toInt()), Float.fromBits(a[5].toInt()), Float.fromBits(a[6].toInt()), a[7], a[8])
    28 -> fn.reinterpret<CFunction<(Float, Float, Float, Int, Float, Float, Long, Long) -> Long>>()(Float.fromBits(a[0].toInt()), Float.fromBits(a[1].toInt()), Float.fromBits(a[2].toInt()), a[3].toInt(), Float.fromBits(a[4].toInt()), Float.fromBits(a[5].toInt()), a[6], a[7])
    29 -> fn.reinterpret<CFunction<(Float, Float, Float, Long, Long, Int, Int, Int, Long) -> Long>>()(Float.fromBits(a[0].toInt()), Float.fromBits(a[1].toInt()), Float.fromBits(a[2].toInt()), a[3], a[4], a[5].toInt(), a[6].toInt(), a[7].toInt(), a[8])
    30 -> fn.reinterpret<CFunction<(Float, Float, Float, Long, Long, Long, Int, Int, Int, Long) -> Long>>()(Float.fromBits(a[0].toInt()), Float.fromBits(a[1].toInt()), Float.fromBits(a[2].toInt()), a[3], a[4], a[5], a[6].toInt(), a[7].toInt(), a[8].toInt(), a[9])
    31 -> fn.reinterpret<CFunction<(Float, Float, Int) -> Long>>()(Float.fromBits(a[0].toInt()), Float.fromBits(a[1].toInt()), a[2].toInt())
    32 -> fn.reinterpret<CFunction<(Float, Float, Int, Float, Int, Int) -> Long>>()(Float.fromBits(a[0].toInt()), Float.fromBits(a[1].toInt()), a[2].toInt(), Float.fromBits(a[3].toInt()), a[4].toInt(), a[5].toInt())
    33 -> fn.reinterpret<CFunction<(Float, Float, Int, Long, Long) -> Long>>()(Float.fromBits(a[0].toInt()), Float.fromBits(a[1].toInt()), a[2].toInt(), a[3], a[4])
    34 -> fn.reinterpret<CFunction<(Float, Float, Long, Long) -> Long>>()(Float.fromBits(a[0].toInt()), Float.fromBits(a[1].toInt()), a[2], a[3])
    35 -> fn.reinterpret<CFunction<(Float, Long) -> Long>>()(Float.fromBits(a[0].toInt()), a[1])
    36 -> fn.reinterpret<CFunction<(Float, Long, Long) -> Long>>()(Float.fromBits(a[0].toInt()), a[1], a[2])
    37 -> fn.reinterpret<CFunction<(Int) -> Int>>()(a[0].toInt()).toLong()
    38 -> fn.reinterpret<CFunction<(Int) -> Long>>()(a[0].toInt())
    39 -> { fn.reinterpret<CFunction<(Int) -> Unit>>()(a[0].toInt()); 0L }
    40 -> fn.reinterpret<CFunction<(Int, Float, Int) -> Long>>()(a[0].toInt(), Float.fromBits(a[1].toInt()), a[2].toInt())
    41 -> fn.reinterpret<CFunction<(Int, Int) -> Int>>()(a[0].toInt(), a[1].toInt()).toLong()
    42 -> fn.reinterpret<CFunction<(Int, Int) -> Long>>()(a[0].toInt(), a[1].toInt())
    43 -> fn.reinterpret<CFunction<(Int, Int, Float) -> Long>>()(a[0].toInt(), a[1].toInt(), Float.fromBits(a[2].toInt()))
    44 -> fn.reinterpret<CFunction<(Int, Int, Float, Long, Long, Long) -> Long>>()(a[0].toInt(), a[1].toInt(), Float.fromBits(a[2].toInt()), a[3], a[4], a[5])
    45 -> fn.reinterpret<CFunction<(Int, Int, Int) -> Long>>()(a[0].toInt(), a[1].toInt(), a[2].toInt())
    46 -> fn.reinterpret<CFunction<(Int, Int, Int, Int, Int, Int) -> Long>>()(a[0].toInt(), a[1].toInt(), a[2].toInt(), a[3].toInt(), a[4].toInt(), a[5].toInt())
    47 -> fn.reinterpret<CFunction<(Int, Int, Int, Int, Long, Int, Long) -> Long>>()(a[0].toInt(), a[1].toInt(), a[2].toInt(), a[3].toInt(), a[4], a[5].toInt(), a[6])
    48 -> fn.reinterpret<CFunction<(Int, Int, Int, Int, Long, Long, Int) -> Long>>()(a[0].toInt(), a[1].toInt(), a[2].toInt(), a[3].toInt(), a[4], a[5], a[6].toInt())
    49 -> fn.reinterpret<CFunction<(Int, Int, Int, Int, Long, Long, Int, Long) -> Long>>()(a[0].toInt(), a[1].toInt(), a[2].toInt(), a[3].toInt(), a[4], a[5], a[6].toInt(), a[7])
    50 -> fn.reinterpret<CFunction<(Int, Int, Long) -> Long>>()(a[0].toInt(), a[1].toInt(), a[2])
    51 -> fn.reinterpret<CFunction<(Int, Int, Long, Float, Float, Int, Int, Int, Int, Long, Long) -> Long>>()(a[0].toInt(), a[1].toInt(), a[2], Float.fromBits(a[3].toInt()), Float.fromBits(a[4].toInt()), a[5].toInt(), a[6].toInt(), a[7].toInt(), a[8].toInt(), a[9], a[10])
    52 -> fn.reinterpret<CFunction<(Int, Int, Long, Int, Int, Int) -> Long>>()(a[0].toInt(), a[1].toInt(), a[2], a[3].toInt(), a[4].toInt(), a[5].toInt())
    53 -> fn.reinterpret<CFunction<(Int, Long) -> Long>>()(a[0].toInt(), a[1])
    54 -> fn.reinterpret<CFunction<(Int, Long, Long) -> Long>>()(a[0].toInt(), a[1], a[2])
    55 -> fn.reinterpret<CFunction<(Int, Long, Long, Long) -> Long>>()(a[0].toInt(), a[1], a[2], a[3])
    56 -> fn.reinterpret<CFunction<(Long) -> Float>>()(a[0]).toRawBits().toLong()
    57 -> fn.reinterpret<CFunction<(Long) -> Int>>()(a[0]).toLong()
    58 -> fn.reinterpret<CFunction<(Long) -> Long>>()(a[0])
    59 -> { fn.reinterpret<CFunction<(Long) -> Unit>>()(a[0]); 0L }
    60 -> fn.reinterpret<CFunction<(Long, Float) -> Int>>()(a[0], Float.fromBits(a[1].toInt())).toLong()
    61 -> fn.reinterpret<CFunction<(Long, Float) -> Long>>()(a[0], Float.fromBits(a[1].toInt()))
    62 -> { fn.reinterpret<CFunction<(Long, Float) -> Unit>>()(a[0], Float.fromBits(a[1].toInt())); 0L }
    63 -> fn.reinterpret<CFunction<(Long, Float, Float) -> Int>>()(a[0], Float.fromBits(a[1].toInt()), Float.fromBits(a[2].toInt())).toLong()
    64 -> fn.reinterpret<CFunction<(Long, Float, Float) -> Long>>()(a[0], Float.fromBits(a[1].toInt()), Float.fromBits(a[2].toInt()))
    65 -> { fn.reinterpret<CFunction<(Long, Float, Float) -> Unit>>()(a[0], Float.fromBits(a[1].toInt()), Float.fromBits(a[2].toInt())); 0L }
    66 -> fn.reinterpret<CFunction<(Long, Float, Float, Float) -> Long>>()(a[0], Float.fromBits(a[1].toInt()), Float.fromBits(a[2].toInt()), Float.fromBits(a[3].toInt()))
    67 -> { fn.reinterpret<CFunction<(Long, Float, Float, Float) -> Unit>>()(a[0], Float.fromBits(a[1].toInt()), Float.fromBits(a[2].toInt()), Float.fromBits(a[3].toInt())); 0L }
    68 -> fn.reinterpret<CFunction<(Long, Float, Float, Float, Float) -> Int>>()(a[0], Float.fromBits(a[1].toInt()), Float.fromBits(a[2].toInt()), Float.fromBits(a[3].toInt()), Float.fromBits(a[4].toInt())).toLong()
    69 -> fn.reinterpret<CFunction<(Long, Float, Float, Float, Float) -> Long>>()(a[0], Float.fromBits(a[1].toInt()), Float.fromBits(a[2].toInt()), Float.fromBits(a[3].toInt()), Float.fromBits(a[4].toInt()))
    70 -> { fn.reinterpret<CFunction<(Long, Float, Float, Float, Float) -> Unit>>()(a[0], Float.fromBits(a[1].toInt()), Float.fromBits(a[2].toInt()), Float.fromBits(a[3].toInt()), Float.fromBits(a[4].toInt())); 0L }
    71 -> { fn.reinterpret<CFunction<(Long, Float, Float, Float, Float, Float) -> Unit>>()(a[0], Float.fromBits(a[1].toInt()), Float.fromBits(a[2].toInt()), Float.fromBits(a[3].toInt()), Float.fromBits(a[4].toInt()), Float.fromBits(a[5].toInt())); 0L }
    72 -> { fn.reinterpret<CFunction<(Long, Float, Float, Float, Float, Float, Float) -> Unit>>()(a[0], Float.fromBits(a[1].toInt()), Float.fromBits(a[2].toInt()), Float.fromBits(a[3].toInt()), Float.fromBits(a[4].toInt()), Float.fromBits(a[5].toInt()), Float.fromBits(a[6].toInt())); 0L }
    73 -> fn.reinterpret<CFunction<(Long, Float, Float, Float, Float, Float, Float, Float, Float, Int, Int) -> Long>>()(a[0], Float.fromBits(a[1].toInt()), Float.fromBits(a[2].toInt()), Float.fromBits(a[3].toInt()), Float.fromBits(a[4].toInt()), Float.fromBits(a[5].toInt()), Float.fromBits(a[6].toInt()), Float.fromBits(a[7].toInt()), Float.fromBits(a[8].toInt()), a[9].toInt(), a[10].toInt())
    74 -> { fn.reinterpret<CFunction<(Long, Float, Float, Float, Float, Float, Float, Int) -> Unit>>()(a[0], Float.fromBits(a[1].toInt()), Float.fromBits(a[2].toInt()), Float.fromBits(a[3].toInt()), Float.fromBits(a[4].toInt()), Float.fromBits(a[5].toInt()), Float.fromBits(a[6].toInt()), a[7].toInt()); 0L }
    75 -> { fn.reinterpret<CFunction<(Long, Float, Float, Float, Float, Float, Float, Int, Long) -> Unit>>()(a[0], Float.fromBits(a[1].toInt()), Float.fromBits(a[2].toInt()), Float.fromBits(a[3].toInt()), Float.fromBits(a[4].toInt()), Float.fromBits(a[5].toInt()), Float.fromBits(a[6].toInt()), a[7].toInt(), a[8]); 0L }
    76 -> fn.reinterpret<CFunction<(Long, Float, Float, Float, Float, Int, Int) -> Long>>()(a[0], Float.fromBits(a[1].toInt()), Float.fromBits(a[2].toInt()), Float.fromBits(a[3].toInt()), Float.fromBits(a[4].toInt()), a[5].toInt(), a[6].toInt())
    77 -> { fn.reinterpret<CFunction<(Long, Float, Float, Float, Float, Int, Int) -> Unit>>()(a[0], Float.fromBits(a[1].toInt()), Float.fromBits(a[2].toInt()), Float.fromBits(a[3].toInt()), Float.fromBits(a[4].toInt()), a[5].toInt(), a[6].toInt()); 0L }
    78 -> fn.reinterpret<CFunction<(Long, Float, Float, Float, Float, Long) -> Int>>()(a[0], Float.fromBits(a[1].toInt()), Float.fromBits(a[2].toInt()), Float.fromBits(a[3].toInt()), Float.fromBits(a[4].toInt()), a[5]).toLong()
    79 -> fn.reinterpret<CFunction<(Long, Float, Float, Float, Float, Long) -> Long>>()(a[0], Float.fromBits(a[1].toInt()), Float.fromBits(a[2].toInt()), Float.fromBits(a[3].toInt()), Float.fromBits(a[4].toInt()), a[5])
    80 -> { fn.reinterpret<CFunction<(Long, Float, Float, Float, Float, Long) -> Unit>>()(a[0], Float.fromBits(a[1].toInt()), Float.fromBits(a[2].toInt()), Float.fromBits(a[3].toInt()), Float.fromBits(a[4].toInt()), a[5]); 0L }
    81 -> { fn.reinterpret<CFunction<(Long, Float, Float, Float, Float, Long, Int, Float, Float, Float, Float, Long, Int, Long) -> Unit>>()(a[0], Float.fromBits(a[1].toInt()), Float.fromBits(a[2].toInt()), Float.fromBits(a[3].toInt()), Float.fromBits(a[4].toInt()), a[5], a[6].toInt(), Float.fromBits(a[7].toInt()), Float.fromBits(a[8].toInt()), Float.fromBits(a[9].toInt()), Float.fromBits(a[10].toInt()), a[11], a[12].toInt(), a[13]); 0L }
    82 -> { fn.reinterpret<CFunction<(Long, Float, Float, Float, Float, Long, Int, Int, Int) -> Unit>>()(a[0], Float.fromBits(a[1].toInt()), Float.fromBits(a[2].toInt()), Float.fromBits(a[3].toInt()), Float.fromBits(a[4].toInt()), a[5], a[6].toInt(), a[7].toInt(), a[8].toInt()); 0L }
    83 -> { fn.reinterpret<CFunction<(Long, Float, Float, Float, Float, Long, Int, Long) -> Unit>>()(a[0], Float.fromBits(a[1].toInt()), Float.fromBits(a[2].toInt()), Float.fromBits(a[3].toInt()), Float.fromBits(a[4].toInt()), a[5], a[6].toInt(), a[7]); 0L }
    84 -> fn.reinterpret<CFunction<(Long, Float, Float, Float, Float, Long, Long, Long, Int) -> Int>>()(a[0], Float.fromBits(a[1].toInt()), Float.fromBits(a[2].toInt()), Float.fromBits(a[3].toInt()), Float.fromBits(a[4].toInt()), a[5], a[6], a[7], a[8].toInt()).toLong()
    85 -> { fn.reinterpret<CFunction<(Long, Float, Float, Float, Int) -> Unit>>()(a[0], Float.fromBits(a[1].toInt()), Float.fromBits(a[2].toInt()), Float.fromBits(a[3].toInt()), a[4].toInt()); 0L }
    86 -> { fn.reinterpret<CFunction<(Long, Float, Float, Float, Int, Int, Float, Float) -> Unit>>()(a[0], Float.fromBits(a[1].toInt()), Float.fromBits(a[2].toInt()), Float.fromBits(a[3].toInt()), a[4].toInt(), a[5].toInt(), Float.fromBits(a[6].toInt()), Float.fromBits(a[7].toInt())); 0L }
    87 -> { fn.reinterpret<CFunction<(Long, Float, Float, Float, Long) -> Unit>>()(a[0], Float.fromBits(a[1].toInt()), Float.fromBits(a[2].toInt()), Float.fromBits(a[3].toInt()), a[4]); 0L }
    88 -> fn.reinterpret<CFunction<(Long, Float, Float, Int) -> Long>>()(a[0], Float.fromBits(a[1].toInt()), Float.fromBits(a[2].toInt()), a[3].toInt())
    89 -> { fn.reinterpret<CFunction<(Long, Float, Float, Int, Int, Float) -> Unit>>()(a[0], Float.fromBits(a[1].toInt()), Float.fromBits(a[2].toInt()), a[3].toInt(), a[4].toInt(), Float.fromBits(a[5].toInt())); 0L }
    90 -> fn.reinterpret<CFunction<(Long, Float, Float, Long) -> Int>>()(a[0], Float.fromBits(a[1].toInt()), Float.fromBits(a[2].toInt()), a[3]).toLong()
    91 -> { fn.reinterpret<CFunction<(Long, Float, Float, Long) -> Unit>>()(a[0], Float.fromBits(a[1].toInt()), Float.fromBits(a[2].toInt()), a[3]); 0L }
    92 -> fn.reinterpret<CFunction<(Long, Float, Float, Long, Int) -> Int>>()(a[0], Float.fromBits(a[1].toInt()), Float.fromBits(a[2].toInt()), a[3], a[4].toInt()).toLong()
    93 -> { fn.reinterpret<CFunction<(Long, Float, Float, Long, Long) -> Unit>>()(a[0], Float.fromBits(a[1].toInt()), Float.fromBits(a[2].toInt()), a[3], a[4]); 0L }
    94 -> { fn.reinterpret<CFunction<(Long, Float, Int) -> Unit>>()(a[0], Float.fromBits(a[1].toInt()), a[2].toInt()); 0L }
    95 -> fn.reinterpret<CFunction<(Long, Float, Int, Int, Long) -> Int>>()(a[0], Float.fromBits(a[1].toInt()), a[2].toInt(), a[3].toInt(), a[4]).toLong()
    96 -> fn.reinterpret<CFunction<(Long, Float, Long) -> Int>>()(a[0], Float.fromBits(a[1].toInt()), a[2]).toLong()
    97 -> { fn.reinterpret<CFunction<(Long, Float, Long) -> Unit>>()(a[0], Float.fromBits(a[1].toInt()), a[2]); 0L }
    98 -> fn.reinterpret<CFunction<(Long, Int) -> Float>>()(a[0], a[1].toInt()).toRawBits().toLong()
    99 -> fn.reinterpret<CFunction<(Long, Int) -> Int>>()(a[0], a[1].toInt()).toLong()
    100 -> fn.reinterpret<CFunction<(Long, Int) -> Long>>()(a[0], a[1].toInt())
    101 -> { fn.reinterpret<CFunction<(Long, Int) -> Unit>>()(a[0], a[1].toInt()); 0L }
    102 -> fn.reinterpret<CFunction<(Long, Int, Float) -> Long>>()(a[0], a[1].toInt(), Float.fromBits(a[2].toInt()))
    103 -> { fn.reinterpret<CFunction<(Long, Int, Float) -> Unit>>()(a[0], a[1].toInt(), Float.fromBits(a[2].toInt())); 0L }
    104 -> { fn.reinterpret<CFunction<(Long, Int, Float, Float, Double) -> Unit>>()(a[0], a[1].toInt(), Float.fromBits(a[2].toInt()), Float.fromBits(a[3].toInt()), Double.fromBits(a[4])); 0L }
    105 -> fn.reinterpret<CFunction<(Long, Int, Int) -> Float>>()(a[0], a[1].toInt(), a[2].toInt()).toRawBits().toLong()
    106 -> fn.reinterpret<CFunction<(Long, Int, Int) -> Int>>()(a[0], a[1].toInt(), a[2].toInt()).toLong()
    107 -> fn.reinterpret<CFunction<(Long, Int, Int) -> Long>>()(a[0], a[1].toInt(), a[2].toInt())
    108 -> { fn.reinterpret<CFunction<(Long, Int, Int) -> Unit>>()(a[0], a[1].toInt(), a[2].toInt()); 0L }
    109 -> { fn.reinterpret<CFunction<(Long, Int, Int, Float, Long) -> Unit>>()(a[0], a[1].toInt(), a[2].toInt(), Float.fromBits(a[3].toInt()), a[4]); 0L }
    110 -> { fn.reinterpret<CFunction<(Long, Int, Int, Int) -> Unit>>()(a[0], a[1].toInt(), a[2].toInt(), a[3].toInt()); 0L }
    111 -> fn.reinterpret<CFunction<(Long, Int, Int, Int, Int) -> Int>>()(a[0], a[1].toInt(), a[2].toInt(), a[3].toInt(), a[4].toInt()).toLong()
    112 -> fn.reinterpret<CFunction<(Long, Int, Int, Int, Int) -> Long>>()(a[0], a[1].toInt(), a[2].toInt(), a[3].toInt(), a[4].toInt())
    113 -> { fn.reinterpret<CFunction<(Long, Int, Int, Int, Int) -> Unit>>()(a[0], a[1].toInt(), a[2].toInt(), a[3].toInt(), a[4].toInt()); 0L }
    114 -> fn.reinterpret<CFunction<(Long, Int, Int, Int, Int, Int) -> Int>>()(a[0], a[1].toInt(), a[2].toInt(), a[3].toInt(), a[4].toInt(), a[5].toInt()).toLong()
    115 -> { fn.reinterpret<CFunction<(Long, Int, Int, Int, Int, Int) -> Unit>>()(a[0], a[1].toInt(), a[2].toInt(), a[3].toInt(), a[4].toInt(), a[5].toInt()); 0L }
    116 -> { fn.reinterpret<CFunction<(Long, Int, Int, Int, Int, Int, Int, Float) -> Unit>>()(a[0], a[1].toInt(), a[2].toInt(), a[3].toInt(), a[4].toInt(), a[5].toInt(), a[6].toInt(), Float.fromBits(a[7].toInt())); 0L }
    117 -> fn.reinterpret<CFunction<(Long, Int, Int, Int, Int, Int, Long, Int, Int, Long, Int) -> Long>>()(a[0], a[1].toInt(), a[2].toInt(), a[3].toInt(), a[4].toInt(), a[5].toInt(), a[6], a[7].toInt(), a[8].toInt(), a[9], a[10].toInt())
    118 -> fn.reinterpret<CFunction<(Long, Int, Int, Int, Int, Long) -> Long>>()(a[0], a[1].toInt(), a[2].toInt(), a[3].toInt(), a[4].toInt(), a[5])
    119 -> fn.reinterpret<CFunction<(Long, Int, Int, Int, Int, Long, Int) -> Int>>()(a[0], a[1].toInt(), a[2].toInt(), a[3].toInt(), a[4].toInt(), a[5], a[6].toInt()).toLong()
    120 -> fn.reinterpret<CFunction<(Long, Int, Int, Int, Int, Long, Int, Int, Int, Long) -> Int>>()(a[0], a[1].toInt(), a[2].toInt(), a[3].toInt(), a[4].toInt(), a[5], a[6].toInt(), a[7].toInt(), a[8].toInt(), a[9]).toLong()
    121 -> fn.reinterpret<CFunction<(Long, Int, Int, Int, Int, Long, Long, Int) -> Int>>()(a[0], a[1].toInt(), a[2].toInt(), a[3].toInt(), a[4].toInt(), a[5], a[6], a[7].toInt()).toLong()
    122 -> { fn.reinterpret<CFunction<(Long, Int, Int, Int, Int, Long, Long, Int) -> Unit>>()(a[0], a[1].toInt(), a[2].toInt(), a[3].toInt(), a[4].toInt(), a[5], a[6], a[7].toInt()); 0L }
    123 -> fn.reinterpret<CFunction<(Long, Int, Int, Int, Int, Long, Long, Int, Int) -> Int>>()(a[0], a[1].toInt(), a[2].toInt(), a[3].toInt(), a[4].toInt(), a[5], a[6], a[7].toInt(), a[8].toInt()).toLong()
    124 -> fn.reinterpret<CFunction<(Long, Int, Int, Int, Int, Long, Long, Int, Int, Int) -> Int>>()(a[0], a[1].toInt(), a[2].toInt(), a[3].toInt(), a[4].toInt(), a[5], a[6], a[7].toInt(), a[8].toInt(), a[9].toInt()).toLong()
    125 -> fn.reinterpret<CFunction<(Long, Int, Int, Int, Long, Int, Float, Float, Float, Float) -> Long>>()(a[0], a[1].toInt(), a[2].toInt(), a[3].toInt(), a[4], a[5].toInt(), Float.fromBits(a[6].toInt()), Float.fromBits(a[7].toInt()), Float.fromBits(a[8].toInt()), Float.fromBits(a[9].toInt()))
    126 -> fn.reinterpret<CFunction<(Long, Int, Int, Long) -> Long>>()(a[0], a[1].toInt(), a[2].toInt(), a[3])
    127 -> { fn.reinterpret<CFunction<(Long, Int, Int, Long) -> Unit>>()(a[0], a[1].toInt(), a[2].toInt(), a[3]); 0L }
    128 -> fn.reinterpret<CFunction<(Long, Int, Int, Long, Long) -> Long>>()(a[0], a[1].toInt(), a[2].toInt(), a[3], a[4])
    129 -> { fn.reinterpret<CFunction<(Long, Int, Int, Long, Long) -> Unit>>()(a[0], a[1].toInt(), a[2].toInt(), a[3], a[4]); 0L }
    130 -> { fn.reinterpret<CFunction<(Long, Int, Int, Long, Long, Long, Int, Long, Int, Long) -> Unit>>()(a[0], a[1].toInt(), a[2].toInt(), a[3], a[4], a[5], a[6].toInt(), a[7], a[8].toInt(), a[9]); 0L }
    131 -> fn.reinterpret<CFunction<(Long, Int, Long) -> Int>>()(a[0], a[1].toInt(), a[2]).toLong()
    132 -> fn.reinterpret<CFunction<(Long, Int, Long) -> Long>>()(a[0], a[1].toInt(), a[2])
    133 -> { fn.reinterpret<CFunction<(Long, Int, Long) -> Unit>>()(a[0], a[1].toInt(), a[2]); 0L }
    134 -> fn.reinterpret<CFunction<(Long, Int, Long, Float, Long) -> Long>>()(a[0], a[1].toInt(), a[2], Float.fromBits(a[3].toInt()), a[4])
    135 -> fn.reinterpret<CFunction<(Long, Int, Long, Int, Long, Int, Int, Int) -> Long>>()(a[0], a[1].toInt(), a[2], a[3].toInt(), a[4], a[5].toInt(), a[6].toInt(), a[7].toInt())
    136 -> fn.reinterpret<CFunction<(Long, Int, Long, Long) -> Long>>()(a[0], a[1].toInt(), a[2], a[3])
    137 -> { fn.reinterpret<CFunction<(Long, Int, Long, Long) -> Unit>>()(a[0], a[1].toInt(), a[2], a[3]); 0L }
    138 -> { fn.reinterpret<CFunction<(Long, Int, Long, Long, Long, Long) -> Unit>>()(a[0], a[1].toInt(), a[2], a[3], a[4], a[5]); 0L }
    139 -> fn.reinterpret<CFunction<(Long, Long) -> Double>>()(a[0], a[1]).toRawBits()
    140 -> fn.reinterpret<CFunction<(Long, Long) -> Int>>()(a[0], a[1]).toLong()
    141 -> fn.reinterpret<CFunction<(Long, Long) -> Long>>()(a[0], a[1])
    142 -> { fn.reinterpret<CFunction<(Long, Long) -> Unit>>()(a[0], a[1]); 0L }
    143 -> fn.reinterpret<CFunction<(Long, Long, Float) -> Long>>()(a[0], a[1], Float.fromBits(a[2].toInt()))
    144 -> { fn.reinterpret<CFunction<(Long, Long, Float) -> Unit>>()(a[0], a[1], Float.fromBits(a[2].toInt())); 0L }
    145 -> { fn.reinterpret<CFunction<(Long, Long, Float, Float) -> Unit>>()(a[0], a[1], Float.fromBits(a[2].toInt()), Float.fromBits(a[3].toInt())); 0L }
    146 -> { fn.reinterpret<CFunction<(Long, Long, Float, Float, Float) -> Unit>>()(a[0], a[1], Float.fromBits(a[2].toInt()), Float.fromBits(a[3].toInt()), Float.fromBits(a[4].toInt())); 0L }
    147 -> { fn.reinterpret<CFunction<(Long, Long, Float, Float, Float, Float) -> Unit>>()(a[0], a[1], Float.fromBits(a[2].toInt()), Float.fromBits(a[3].toInt()), Float.fromBits(a[4].toInt()), Float.fromBits(a[5].toInt())); 0L }
    148 -> { fn.reinterpret<CFunction<(Long, Long, Float, Float, Float, Float, Float, Float, Float, Float, Int, Int, Long, Int) -> Unit>>()(a[0], a[1], Float.fromBits(a[2].toInt()), Float.fromBits(a[3].toInt()), Float.fromBits(a[4].toInt()), Float.fromBits(a[5].toInt()), Float.fromBits(a[6].toInt()), Float.fromBits(a[7].toInt()), Float.fromBits(a[8].toInt()), Float.fromBits(a[9].toInt()), a[10].toInt(), a[11].toInt(), a[12], a[13].toInt()); 0L }
    149 -> { fn.reinterpret<CFunction<(Long, Long, Float, Float, Float, Float, Float, Float, Float, Int, Int, Int) -> Unit>>()(a[0], a[1], Float.fromBits(a[2].toInt()), Float.fromBits(a[3].toInt()), Float.fromBits(a[4].toInt()), Float.fromBits(a[5].toInt()), Float.fromBits(a[6].toInt()), Float.fromBits(a[7].toInt()), Float.fromBits(a[8].toInt()), a[9].toInt(), a[10].toInt(), a[11].toInt()); 0L }
    150 -> { fn.reinterpret<CFunction<(Long, Long, Float, Float, Float, Float, Int) -> Unit>>()(a[0], a[1], Float.fromBits(a[2].toInt()), Float.fromBits(a[3].toInt()), Float.fromBits(a[4].toInt()), Float.fromBits(a[5].toInt()), a[6].toInt()); 0L }
    151 -> fn.reinterpret<CFunction<(Long, Long, Float, Float, Float, Float, Long) -> Long>>()(a[0], a[1], Float.fromBits(a[2].toInt()), Float.fromBits(a[3].toInt()), Float.fromBits(a[4].toInt()), Float.fromBits(a[5].toInt()), a[6])
    152 -> { fn.reinterpret<CFunction<(Long, Long, Float, Float, Float, Float, Long) -> Unit>>()(a[0], a[1], Float.fromBits(a[2].toInt()), Float.fromBits(a[3].toInt()), Float.fromBits(a[4].toInt()), Float.fromBits(a[5].toInt()), a[6]); 0L }
    153 -> { fn.reinterpret<CFunction<(Long, Long, Float, Float, Int) -> Unit>>()(a[0], a[1], Float.fromBits(a[2].toInt()), Float.fromBits(a[3].toInt()), a[4].toInt()); 0L }
    154 -> { fn.reinterpret<CFunction<(Long, Long, Float, Float, Int, Int, Long) -> Unit>>()(a[0], a[1], Float.fromBits(a[2].toInt()), Float.fromBits(a[3].toInt()), a[4].toInt(), a[5].toInt(), a[6]); 0L }
    155 -> { fn.reinterpret<CFunction<(Long, Long, Float, Float, Long) -> Unit>>()(a[0], a[1], Float.fromBits(a[2].toInt()), Float.fromBits(a[3].toInt()), a[4]); 0L }
    156 -> { fn.reinterpret<CFunction<(Long, Long, Float, Float, Long, Long) -> Unit>>()(a[0], a[1], Float.fromBits(a[2].toInt()), Float.fromBits(a[3].toInt()), a[4], a[5]); 0L }
    157 -> { fn.reinterpret<CFunction<(Long, Long, Float, Int, Long) -> Unit>>()(a[0], a[1], Float.fromBits(a[2].toInt()), a[3].toInt(), a[4]); 0L }
    158 -> fn.reinterpret<CFunction<(Long, Long, Int) -> Int>>()(a[0], a[1], a[2].toInt()).toLong()
    159 -> fn.reinterpret<CFunction<(Long, Long, Int) -> Long>>()(a[0], a[1], a[2].toInt())
    160 -> { fn.reinterpret<CFunction<(Long, Long, Int) -> Unit>>()(a[0], a[1], a[2].toInt()); 0L }
    161 -> { fn.reinterpret<CFunction<(Long, Long, Int, Float, Float, Long) -> Unit>>()(a[0], a[1], a[2].toInt(), Float.fromBits(a[3].toInt()), Float.fromBits(a[4].toInt()), a[5]); 0L }
    162 -> fn.reinterpret<CFunction<(Long, Long, Int, Int) -> Int>>()(a[0], a[1], a[2].toInt(), a[3].toInt()).toLong()
    163 -> fn.reinterpret<CFunction<(Long, Long, Int, Int) -> Long>>()(a[0], a[1], a[2].toInt(), a[3].toInt())
    164 -> { fn.reinterpret<CFunction<(Long, Long, Int, Int) -> Unit>>()(a[0], a[1], a[2].toInt(), a[3].toInt()); 0L }
    165 -> fn.reinterpret<CFunction<(Long, Long, Int, Int, Int) -> Int>>()(a[0], a[1], a[2].toInt(), a[3].toInt(), a[4].toInt()).toLong()
    166 -> { fn.reinterpret<CFunction<(Long, Long, Int, Int, Int) -> Unit>>()(a[0], a[1], a[2].toInt(), a[3].toInt(), a[4].toInt()); 0L }
    167 -> fn.reinterpret<CFunction<(Long, Long, Int, Int, Int, Int) -> Int>>()(a[0], a[1], a[2].toInt(), a[3].toInt(), a[4].toInt(), a[5].toInt()).toLong()
    168 -> { fn.reinterpret<CFunction<(Long, Long, Int, Int, Int, Int) -> Unit>>()(a[0], a[1], a[2].toInt(), a[3].toInt(), a[4].toInt(), a[5].toInt()); 0L }
    169 -> { fn.reinterpret<CFunction<(Long, Long, Int, Int, Int, Int, Float, Float, Float, Float, Int, Long) -> Unit>>()(a[0], a[1], a[2].toInt(), a[3].toInt(), a[4].toInt(), a[5].toInt(), Float.fromBits(a[6].toInt()), Float.fromBits(a[7].toInt()), Float.fromBits(a[8].toInt()), Float.fromBits(a[9].toInt()), a[10].toInt(), a[11]); 0L }
    170 -> fn.reinterpret<CFunction<(Long, Long, Int, Int, Int, Int, Int) -> Int>>()(a[0], a[1], a[2].toInt(), a[3].toInt(), a[4].toInt(), a[5].toInt(), a[6].toInt()).toLong()
    171 -> fn.reinterpret<CFunction<(Long, Long, Int, Int, Int, Long, Long) -> Long>>()(a[0], a[1], a[2].toInt(), a[3].toInt(), a[4].toInt(), a[5], a[6])
    172 -> fn.reinterpret<CFunction<(Long, Long, Int, Int, Long, Int) -> Long>>()(a[0], a[1], a[2].toInt(), a[3].toInt(), a[4], a[5].toInt())
    173 -> fn.reinterpret<CFunction<(Long, Long, Int, Int, Long, Long) -> Long>>()(a[0], a[1], a[2].toInt(), a[3].toInt(), a[4], a[5])
    174 -> fn.reinterpret<CFunction<(Long, Long, Int, Long) -> Float>>()(a[0], a[1], a[2].toInt(), a[3]).toRawBits().toLong()
    175 -> fn.reinterpret<CFunction<(Long, Long, Int, Long) -> Int>>()(a[0], a[1], a[2].toInt(), a[3]).toLong()
    176 -> fn.reinterpret<CFunction<(Long, Long, Int, Long) -> Long>>()(a[0], a[1], a[2].toInt(), a[3])
    177 -> { fn.reinterpret<CFunction<(Long, Long, Int, Long) -> Unit>>()(a[0], a[1], a[2].toInt(), a[3]); 0L }
    178 -> fn.reinterpret<CFunction<(Long, Long, Int, Long, Int, Int) -> Long>>()(a[0], a[1], a[2].toInt(), a[3], a[4].toInt(), a[5].toInt())
    179 -> { fn.reinterpret<CFunction<(Long, Long, Int, Long, Long) -> Unit>>()(a[0], a[1], a[2].toInt(), a[3], a[4]); 0L }
    180 -> fn.reinterpret<CFunction<(Long, Long, Long) -> Int>>()(a[0], a[1], a[2]).toLong()
    181 -> fn.reinterpret<CFunction<(Long, Long, Long) -> Long>>()(a[0], a[1], a[2])
    182 -> { fn.reinterpret<CFunction<(Long, Long, Long) -> Unit>>()(a[0], a[1], a[2]); 0L }
    183 -> fn.reinterpret<CFunction<(Long, Long, Long, Int) -> Int>>()(a[0], a[1], a[2], a[3].toInt()).toLong()
    184 -> fn.reinterpret<CFunction<(Long, Long, Long, Int) -> Long>>()(a[0], a[1], a[2], a[3].toInt())
    185 -> { fn.reinterpret<CFunction<(Long, Long, Long, Int) -> Unit>>()(a[0], a[1], a[2], a[3].toInt()); 0L }
    186 -> { fn.reinterpret<CFunction<(Long, Long, Long, Int, Float, Float, Long) -> Unit>>()(a[0], a[1], a[2], a[3].toInt(), Float.fromBits(a[4].toInt()), Float.fromBits(a[5].toInt()), a[6]); 0L }
    187 -> fn.reinterpret<CFunction<(Long, Long, Long, Int, Int, Int) -> Int>>()(a[0], a[1], a[2], a[3].toInt(), a[4].toInt(), a[5].toInt()).toLong()
    188 -> fn.reinterpret<CFunction<(Long, Long, Long, Int, Long) -> Long>>()(a[0], a[1], a[2], a[3].toInt(), a[4])
    189 -> { fn.reinterpret<CFunction<(Long, Long, Long, Int, Long) -> Unit>>()(a[0], a[1], a[2], a[3].toInt(), a[4]); 0L }
    190 -> { fn.reinterpret<CFunction<(Long, Long, Long, Int, Long, Float, Long) -> Unit>>()(a[0], a[1], a[2], a[3].toInt(), a[4], Float.fromBits(a[5].toInt()), a[6]); 0L }
    191 -> fn.reinterpret<CFunction<(Long, Long, Long, Int, Long, Int) -> Long>>()(a[0], a[1], a[2], a[3].toInt(), a[4], a[5].toInt())
    192 -> fn.reinterpret<CFunction<(Long, Long, Long, Int, Long, Int, Float, Float, Float) -> Long>>()(a[0], a[1], a[2], a[3].toInt(), a[4], a[5].toInt(), Float.fromBits(a[6].toInt()), Float.fromBits(a[7].toInt()), Float.fromBits(a[8].toInt()))
    193 -> { fn.reinterpret<CFunction<(Long, Long, Long, Int, Long, Long) -> Unit>>()(a[0], a[1], a[2], a[3].toInt(), a[4], a[5]); 0L }
    194 -> fn.reinterpret<CFunction<(Long, Long, Long, Long) -> Int>>()(a[0], a[1], a[2], a[3]).toLong()
    195 -> fn.reinterpret<CFunction<(Long, Long, Long, Long) -> Long>>()(a[0], a[1], a[2], a[3])
    196 -> { fn.reinterpret<CFunction<(Long, Long, Long, Long) -> Unit>>()(a[0], a[1], a[2], a[3]); 0L }
    197 -> fn.reinterpret<CFunction<(Long, Long, Long, Long, Int) -> Int>>()(a[0], a[1], a[2], a[3], a[4].toInt()).toLong()
    198 -> { fn.reinterpret<CFunction<(Long, Long, Long, Long, Int, Long) -> Unit>>()(a[0], a[1], a[2], a[3], a[4].toInt(), a[5]); 0L }
    199 -> { fn.reinterpret<CFunction<(Long, Long, Long, Long, Long, Long, Int, Long, Int, Float, Long) -> Unit>>()(a[0], a[1], a[2], a[3], a[4], a[5], a[6].toInt(), a[7], a[8].toInt(), Float.fromBits(a[9].toInt()), a[10]); 0L }
    200 -> { fn.reinterpret<CFunction<(Long, Long, Long, Long, Long, Long, Long) -> Unit>>()(a[0], a[1], a[2], a[3], a[4], a[5], a[6]); 0L }
    else -> error("unknown skia call shape $shape")
}
