package dev.ide.android

import com.android.tools.r8.D8
import com.android.tools.r8.D8Command
import com.android.tools.r8.OutputMode
import dalvik.system.InMemoryDexClassLoader
import dev.ide.jvm.AsmPeerFactory
import java.nio.ByteBuffer
import java.nio.file.Files

/**
 * A peer factory for ART: reuses [AsmPeerFactory]'s class-file generation but converts the generated bytes to
 * dex with the bundled in-process D8 before loading them (ART's class loaders reject class-file bytecode).
 * The generated trampolines use no language feature that needs desugaring, so D8 runs without a library or
 * classpath.
 */
class DexPeerFactory : AsmPeerFactory() {

    override fun define(binaryName: String, bytes: ByteArray): Class<*> {
        val dir = Files.createTempDirectory("vm-peer")
        try {
            Files.write(dir.resolve("Peer.class"), bytes)
            D8.run(
                D8Command.builder()
                    .addProgramFiles(dir.resolve("Peer.class"))
                    .setMinApiLevel(26)
                    .setDisableDesugaring(true)
                    .setOutput(dir, OutputMode.DexIndexed)
                    .build(),
            )
            val dex = Files.readAllBytes(dir.resolve("classes.dex"))
            return InMemoryDexClassLoader(ByteBuffer.wrap(dex), javaClass.classLoader).loadClass(binaryName)
        } finally {
            dir.toFile().deleteRecursively()
        }
    }
}
