package dev.ide.android.support.crashlytics

import java.nio.file.Path

/**
 * The on-device equivalent of the `com.google.firebase.crashlytics` Gradle plugin's
 * `injectCrashlyticsMappingFileId` task: the plugin half the Crashlytics runtime requires but that
 * nothing in a project's build files names (applying the plugin is the opt-in, and CodeAssist has no
 * Gradle plugins; see the Hilt case in `docs/kotlin-compiler-plugins-and-codegen.md`).
 *
 * Without it every app that merely has `firebase-crashlytics` on its classpath dies on startup, before any
 * user code runs, because `FirebaseInitProvider` initializes Crashlytics from a `<provider>` in the merged
 * manifest and `CrashlyticsCore.onPreExecute` throws:
 *
 * ```
 * java.lang.RuntimeException: Unable to get provider com.google.firebase.provider.FirebaseInitProvider:
 *   java.lang.IllegalStateException: The Crashlytics build ID is missing. This occurs when the Crashlytics
 *   Gradle plugin is missing from your app's build configuration.
 * ```
 *
 * The runtime contract (read off `firebase-crashlytics`' own bytecode, `CommonUtils`/`CrashlyticsCore`):
 * the build id is the string resource [MAPPING_FILE_ID_RESOURCE] (legacy fallback
 * `com.crashlytics.android.build_id`), looked up by NAME via `Resources.getIdentifier`, so it only has to
 * exist in the app's merged resource table, so no `R` constant is involved. It is required unless the bool
 * resource `com.google.firebase.crashlytics.RequireBuildId` is set false.
 *
 * Pure string/path logic (no Android types), so it is unit-testable without an SDK.
 */
object Crashlytics {

    /** The Maven coordinate whose presence on the runtime classpath makes the build id mandatory. */
    const val COORDINATE = "com.google.firebase:firebase-crashlytics"

    /** The string resource `CommonUtils.getMappingFileId` reads (by name, not by `R` id). */
    const val MAPPING_FILE_ID_RESOURCE = "com.google.firebase.crashlytics.mapping_file_id"

    /** The generated file name, matching the Gradle plugin's `InjectMappingFileIdTask` byte for byte. */
    const val RESOURCE_FILE_NAME = "com_google_firebase_crashlytics_mappingfileid.xml"

    /**
     * The id the real plugin writes when mapping-file upload is off (its `useBlankMappingFileId` path).
     * CodeAssist never uploads a ProGuard/R8 mapping file to Crashlytics, so a *unique* id would buy
     * nothing and would rewrite this resource on every build, dirtying the resource merge each time.
     * A constant keeps the task's output stable, which is what incremental builds want.
     */
    const val BLANK_MAPPING_FILE_ID = "00000000000000000000000000000000"

    /**
     * True when `firebase-crashlytics` is on [classpath]. Deliberately NOT the "directly declares it" rule
     * used for Hilt: Crashlytics initializes itself from the manifest merged out of its own AAR, so an app
     * that reaches it only TRANSITIVELY (through any Firebase convenience artifact) crashes just the same.
     *
     * Matched on the resolver's Maven-layout cache path (`…/com/google/firebase/firebase-crashlytics/<v>/…`)
     * because a transitive artifact is not its own `LibraryDependency` (the whole resolved closure is
     * stored under the primary coordinate's library). Paths are model data, so this opens no files: it is
     * safe to call while the task graph is being built, before a first clean build has exploded any AAR.
     */
    private const val FILE_PREFIX = "firebase-crashlytics-"

    fun onClasspath(classpath: List<Path>): Boolean {
        val marker = "${COORDINATE.substringBefore(':').replace('.', '/')}/${COORDINATE.substringAfter(':')}/"
        return classpath.any { p ->
            val s = p.toString().replace('\\', '/')
            if (s.contains("/$marker")) return@any true
            // A local `libs/firebase-crashlytics-<v>.aar` has no Maven layout to match on. Require a DIGIT
            // after the prefix so the sibling artifacts (`-ndk-`, `-buildtools-`) don't count as the runtime.
            val file = s.substringAfterLast('/')
            file.startsWith(FILE_PREFIX) && file.getOrNull(FILE_PREFIX.length)?.isDigit() == true
        }
    }

    /** The generated `values/` XML, matching the Gradle plugin's `XmlResourceUtils` output. */
    fun mappingFileIdXml(mappingFileId: String = BLANK_MAPPING_FILE_ID): String =
        "<?xml version=\"1.0\" encoding=\"utf-8\"?>\n" +
            "<resources xmlns:tools=\"http://schemas.android.com/tools\">\n" +
            "<!--\n" +
            "  This file is automatically generated by Crashlytics to uniquely \n" +
            "  identify the mapping file for your Android application.\n" +
            "\n" +
            "  Do NOT modify or commit to source control!\n" +
            "-->\n" +
            "<string name=\"$MAPPING_FILE_ID_RESOURCE\" tools:ignore=\"UnusedResources,TypographyDashes\" " +
            "translatable=\"false\">$mappingFileId</string>\n" +
            "</resources>\n"
}
