import org.jetbrains.kotlin.gradle.dsl.JvmTarget

// jvm-vm: a closed-world JVM bytecode interpreter that runs where there is no JVM.
//
// `:jvm-interp` interprets a program and hands everything else (the JDK, Kotlin, the bundled Compose) to the
// host JVM by reflection. iOS has no JVM to hand anything to and no reflection to hand it with, and a preview
// that should honour the PROJECT's library versions cannot lean on whatever the IDE bundles anyway. So this VM
// interprets every class it is given, the Kotlin standard library and Compose included, and implements only
// the JDK itself, in Kotlin, as a fixed floor (see JdkLibrary).
//
// The tests run the same compiled fixtures through the VM on the JVM (where the real call is the oracle) and on
// the iOS simulator (where it is the only way they can run at all).
plugins {
    alias(libs.plugins.kotlin.multiplatform)
}

kotlin {
    jvm {
        compilerOptions { jvmTarget.set(JvmTarget.JVM_17) }
    }

    // skikoBridges.def is a table of every skia C bridge (see tools/skiko_bridges_def.py): referencing them
    // keeps them in the link, and the table is how the VM looks them up by name.
    listOf(iosSimulatorArm64(), iosArm64()).forEach { target ->
        target.compilations.getByName("main").cinterops.create("skikoBridges")
    }

    sourceSets {
        commonMain.dependencies {
            // Jars and the file system, multiplatform: ZipArchive + dev.ide.platform.
            implementation(project(":kotlin-classfile"))
        }

        commonTest.dependencies {
            implementation(kotlin("test"))
        }

        // The fixtures, compiled for real: the oracle the JVM tests compare the VM against.
        jvmTest.dependencies {
            implementation(project(":jvm-vm-fixtures"))
        }

        val iosMain = create("iosMain") {
            dependsOn(getByName("commonMain"))
            // skia itself, as skiko's iOS build links it: the C functions the interpreted skiko calls.
            dependencies { implementation(libs.skiko) }
        }
        getByName("iosSimulatorArm64Main").dependsOn(iosMain)
        getByName("iosArm64Main").dependsOn(iosMain)
        val iosTest = create("iosTest") { dependsOn(getByName("commonTest")) }
        getByName("iosSimulatorArm64Test").dependsOn(iosTest)
        getByName("iosArm64Test").dependsOn(iosTest)
    }
}

dependencies {
    "jvmTestImplementation"(platform(libs.junit.bom))
    "jvmTestImplementation"(libs.junit.jupiter)
    "jvmTestRuntimeOnly"(libs.junit.platform.launcher)
}

// The class path the VM tests interpret: the fixtures jar and everything it needs at run time (the Kotlin
// standard library, the Compose runtime, coroutines). Written as a Kotlin source so the simulator, which
// inherits no environment from Gradle, can find the same jars by absolute path; the simulator shares the
// host's file system.
val generateVmTestClasspath by tasks.registering {
    val runtime = configurations.named("jvmTestRuntimeClasspath")
    inputs.files(runtime)
    val out = layout.buildDirectory.dir("generated/vmTestClasspath/kotlin")
    outputs.dir(out)
    doLast {
        val entries = runtime.get().files.map { it.absolutePath }.sorted()
        val file = out.get().file("dev/ide/vm/TestClasspath.kt").asFile
        file.parentFile.mkdirs()
        file.writeText(buildString {
            appendLine("package dev.ide.vm")
            appendLine()
            appendLine("/** Generated by :jvm-vm's build: the jars the VM tests interpret. */")
            appendLine("internal object TestClasspath {")
            appendLine("    val entries: List<String> = listOf(")
            for (e in entries) appendLine("        \"" + e.replace("\\", "/") + "\",")
            appendLine("    )")
            appendLine("    val outputDir: String = \"" + layout.buildDirectory.dir("vm-test-output").get().asFile.absolutePath + "\"")
            appendLine("}")
        })
    }
}
kotlin.sourceSets.named("commonTest") { kotlin.srcDir(generateVmTestClasspath) }

tasks.named<Test>("jvmTest") {
    useJUnitPlatform()
    maxHeapSize = "2g"
}
