name: "Feature Request"
description: "Suggest an idea for this project"
title: "[Feature]: "
labels: ["enhancement", "feature"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request!
        Please provide a proper title and description to the issue.
  - type: textarea
    id: feature-request-related-to-a-problem
    attributes:
      label: Is your feature request related to a problem? Please describe.
      description: A clear and concise description of what the problem is.
      placeholder: Ex. I'm always frustrated when [...]
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of any alternative solutions or features you've considered.
      placeholder: 
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
      placeholder: 
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/scto/CodeAssist/blob/main/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true