package dev.ide.jvm

import org.objectweb.asm.ClassWriter
import org.objectweb.asm.Opcodes
import org.objectweb.asm.Type
import org.objectweb.asm.commons.GeneratorAdapter
import java.lang.reflect.InvocationHandler
import java.lang.reflect.Proxy
import java.util.concurrent.ConcurrentHashMap
import java.util.concurrent.atomic.AtomicInteger
import org.objectweb.asm.commons.Method as AsmMethod

/**
 * A [PeerFactory] for the JVM. It generates, with ASM, a real subclass of the interpreted class's real
 * supertype that also implements the class's real interfaces and [VmPeer]. Each overridden method boxes its
 * arguments and forwards to a [PeerDispatch] (which runs the interpreted body); a `super$name` trampoline
 * invokes the real implementation so an interpreted `super` call reaches it; an abstract supertype method the
 * interpreted class does not implement is stubbed to throw so the peer is concrete. The generated constructor
 * invokes the exact real superclass constructor the interpreted constructor called, so a superclass without a
 * no-argument constructor is initialized correctly. Generated classes are loaded by a child class loader and
 * cached.
 *
 * A peer whose interpreted class only IMPLEMENTS real interfaces (its nearest real superclass is `Object`) is
 * realized as a [java.lang.reflect.Proxy] instead of a generated class — the JDK reflection feature, not a
 * loaded/generated class. This avoids defining a class at all for the common case (an interpreted `Runnable`/
 * `Comparator`/`Callable` handed to a platform API), which on Android means no runtime dex generation for it.
 * Only a peer that EXTENDS a real concrete class (e.g. `View`, `Thread`) still needs a generated subclass.
 *
 * On Android, where class-file bytecode cannot be loaded, a subclass overrides [define] to convert the
 * generated bytes to dex before loading them.
 */
open class AsmPeerFactory(
    private val parent: ClassLoader = AsmPeerFactory::class.java.classLoader,
) : PeerFactory {

    private val loader = PeerClassLoader(parent)
    private val generated = ConcurrentHashMap<String, Class<*>>()
    private val reflectionClasses = ConcurrentHashMap<String, Class<*>>()
    private val reflectionNames = ConcurrentHashMap<Class<*>, String>()
    private val counter = AtomicInteger()

    override fun createPeer(
        vmObject: Any,
        spec: PeerSpec,
        dispatch: PeerDispatch,
        superConstructorDescriptor: String,
        superConstructorArgs: List<Any?>,
    ): Any {
        if (isProxyable(spec)) return createProxyPeer(vmObject, spec, dispatch)
        val cls = peerClass(spec, superConstructorDescriptor)
        val ctor = cls.declaredConstructors.first()
        return ctor.newInstance(vmObject, dispatch, *superConstructorArgs.toTypedArray())
    }

    /** A peer is Proxy-realizable when its interpreted class only implements real interfaces (its nearest real
     *  superclass is `Object`). A concrete-class extension (`View`, `Thread`) still needs a generated subclass. */
    private fun isProxyable(spec: PeerSpec): Boolean =
        spec.superClass == Any::class.java && spec.interfaces.isNotEmpty()

    /**
     * Realize an interface-only peer as a [Proxy] of the real interfaces + [VmPeer]. The handler routes: an
     * overridden interface method to [dispatch] (which runs the interpreted body); a non-overridden DEFAULT
     * method to its real default body via [InvocationHandler.invokeDefault] (whose self-calls come back through
     * this handler, so composition stays correct); an unimplemented abstract method to an `AbstractMethodError`;
     * and `vmObject()`/`Object` methods locally. No class is generated or loaded — on Android this avoids
     * runtime dex generation for the common case (an interpreted `Runnable`/`Comparator`/`Callable`).
     */
    private fun createProxyPeer(vmObject: Any, spec: PeerSpec, dispatch: PeerDispatch): Any {
        val overridden = spec.methods.mapTo(HashSet()) { it.name + it.descriptor }
        val stubs = spec.abstractStubs.mapTo(HashSet()) { it.name + it.descriptor }
        val interfaces = (spec.interfaces + VmPeer::class.java).toTypedArray()
        lateinit var proxy: Any
        val handler = InvocationHandler { _, method, rawArgs ->
            val args = rawArgs ?: EMPTY_ARGS
            val descriptor = Type.getMethodDescriptor(method)
            val key = method.name + descriptor
            when {
                method.declaringClass == VmPeer::class.java -> vmObject
                key in overridden -> dispatch.invoke(proxy, vmObject, method.name, descriptor, args)
                key in stubs -> throw AbstractMethodError("the interpreted class does not override $key")
                method.isDefault -> InvocationHandler.invokeDefault(proxy, method, *args)
                method.name == "toString" && args.isEmpty() -> "VmPeer(${spec.className})"
                method.name == "hashCode" && args.isEmpty() -> System.identityHashCode(proxy)
                method.name == "equals" && args.size == 1 -> args[0] === proxy
                else -> dispatch.invoke(proxy, vmObject, method.name, descriptor, args)
            }
        }
        proxy = Proxy.newProxyInstance(parent, interfaces, handler)
        return proxy
    }

    override fun peerClass(spec: PeerSpec, superConstructorDescriptor: String): Class<*> =
        generated.getOrPut(key(spec, superConstructorDescriptor)) { definePeer(spec, superConstructorDescriptor) }

    override fun reflectionClass(className: String, constructorDescriptors: List<String>): Class<*> =
        reflectionClasses.getOrPut(className) { defineReflectionClass(className, constructorDescriptors) }

    override fun interpretedNameOf(cls: Class<*>): String? = reflectionNames[cls]

    /** A minimal real class extending `Object` that stands for an interpreted type in reflection, with a public
     *  constructor per descriptor so `getConstructor` matches. Never instantiated (newInstance is intercepted),
     *  so each constructor simply invokes `Object.<init>` and returns. */
    private fun defineReflectionClass(className: String, ctorDescriptors: List<String>): Class<*> {
        val traceable = className.replace('/', '_').replace('$', '_')
        val internalName = "dev/ide/jvm/reflect/${traceable}_R${counter.incrementAndGet()}"
        val cw = object : ClassWriter(COMPUTE_FRAMES) {
            override fun getClassLoader(): ClassLoader = parent
        }
        cw.visit(Opcodes.V17, Opcodes.ACC_PUBLIC, internalName, null, "java/lang/Object", null)
        val descriptors = ctorDescriptors.ifEmpty { listOf("()V") }
        for (desc in descriptors) {
            val g = GeneratorAdapter(Opcodes.ACC_PUBLIC, AsmMethod("<init>", desc), null, null, cw)
            g.loadThis()
            g.invokeConstructor(OBJECT, AsmMethod("<init>", "()V"))
            g.returnValue()
            g.endMethod()
        }
        cw.visitEnd()
        val cls = define(internalName.replace('/', '.'), cw.toByteArray())
        reflectionNames[cls] = className
        return cls
    }

    private fun key(spec: PeerSpec, superCtor: String): String =
        spec.superClass.name + "|" +
            spec.interfaces.joinToString(",") { it.name } + "|" +
            spec.methods.joinToString(",") { it.name + it.descriptor } + "|" +
            spec.abstractStubs.joinToString(",") { it.name + it.descriptor } + "|" +
            superCtor

    private fun definePeer(spec: PeerSpec, superCtorDescriptor: String): Class<*> {
        val traceableName = spec.className.replace('/', '_').replace('$', '_')
        val internalName = "dev/ide/jvm/peers/${traceableName}_Peer${counter.incrementAndGet()}"
        val peerType = Type.getObjectType(internalName)
        val superType = Type.getType(spec.superClass)
        // An interface that owns a trampolined default method must be a DIRECT superinterface: `invokespecial`
        // on an interface method is rejected by the verifier when the interface is only indirectly implemented.
        val interfaceInternals = LinkedHashSet<String>().apply {
            spec.interfaces.forEach { add(Type.getInternalName(it)) }
            spec.methods.forEach { if (it.ownerIsInterface) add(it.ownerInternalName) }
            add(Type.getInternalName(VmPeer::class.java))
        }.toTypedArray()

        val cw = object : ClassWriter(COMPUTE_FRAMES) {
            // Frame computation resolves common supertypes by loading classes; use the loader that sees the
            // real supertype, the interfaces, and this module's types.
            override fun getClassLoader(): ClassLoader = parent
        }
        cw.visit(Opcodes.V17, Opcodes.ACC_PUBLIC, internalName, null, Type.getInternalName(spec.superClass), interfaceInternals)

        cw.visitField(Opcodes.ACC_PRIVATE or Opcodes.ACC_FINAL, VM_FIELD, OBJECT.descriptor, null, null).visitEnd()
        cw.visitField(Opcodes.ACC_PRIVATE or Opcodes.ACC_FINAL, DISPATCH_FIELD, DISPATCH.descriptor, null, null).visitEnd()

        generateConstructor(cw, peerType, superType, superCtorDescriptor)
        generateVmObjectAccessor(cw, peerType)
        for (m in spec.methods) {
            generateOverride(cw, peerType, m)
            generateSuperTrampoline(cw, m)
        }
        for (m in spec.abstractStubs) generateAbstractStub(cw, m)

        cw.visitEnd()
        return define(internalName.replace('/', '.'), cw.toByteArray())
    }

    /** Turns the generated class-file [bytes] into a loadable class. The JVM defines them directly; an Android
     *  factory converts them to dex first (ART cannot define class-file bytecode). */
    protected open fun define(binaryName: String, bytes: ByteArray): Class<*> = loader.define(binaryName, bytes)

    /**
     * `<init>(Object vm, PeerDispatch dispatch, <super constructor parameters>)`: store the two fields, then
     * invoke the real superclass constructor with the trailing parameters. The fields are assigned BEFORE the
     * super call (the verifier permits `putfield` on an uninitialized `this` for fields the current class
     * declares) because a real superclass constructor may call an overridden virtual method, as an
     * `android.view.View`/`TextView` constructor does, and that override must find the dispatch in place.
     */
    private fun generateConstructor(cw: ClassWriter, peerType: Type, superType: Type, superCtorDescriptor: String) {
        val superParams = Type.getArgumentTypes(superCtorDescriptor)
        val ctorDescriptor = "(${OBJECT.descriptor}${DISPATCH.descriptor}${superParams.joinToString("") { it.descriptor }})V"
        val ctor = GeneratorAdapter(Opcodes.ACC_PUBLIC, AsmMethod("<init>", ctorDescriptor), null, null, cw)
        ctor.loadThis(); ctor.loadArg(0); ctor.putField(peerType, VM_FIELD, OBJECT)
        ctor.loadThis(); ctor.loadArg(1); ctor.putField(peerType, DISPATCH_FIELD, DISPATCH)
        ctor.loadThis()
        for (i in superParams.indices) ctor.loadArg(2 + i)
        ctor.invokeConstructor(superType, AsmMethod("<init>", superCtorDescriptor))
        ctor.returnValue()
        ctor.endMethod()
    }

    private fun generateVmObjectAccessor(cw: ClassWriter, peerType: Type) {
        val g = GeneratorAdapter(Opcodes.ACC_PUBLIC, AsmMethod("vmObject", "()${OBJECT.descriptor}"), null, null, cw)
        g.loadThis()
        g.getField(peerType, VM_FIELD, OBJECT)
        g.returnValue()
        g.endMethod()
    }

    /** An override that boxes its arguments and calls `dispatch.invoke(this, vm, name, descriptor, args)`, then
     *  unboxes the result to the method's return type. `this` (the peer) is passed first so the runtime can
     *  link it to the interpreted instance on the first dispatch, which may occur mid-construction (a real
     *  super constructor calling an overridden method). */
    private fun generateOverride(cw: ClassWriter, peerType: Type, m: PeerMethod) {
        val method = AsmMethod(m.name, m.descriptor)
        val g = GeneratorAdapter(Opcodes.ACC_PUBLIC, method, null, null, cw)
        g.loadThis(); g.getField(peerType, DISPATCH_FIELD, DISPATCH)
        g.loadThis()                                        // peer (this)
        g.loadThis(); g.getField(peerType, VM_FIELD, OBJECT)
        g.push(m.name)
        g.push(m.descriptor)
        g.loadArgArray()
        g.invokeInterface(DISPATCH, INVOKE)
        val returnType = method.returnType
        if (returnType == Type.VOID_TYPE) g.pop() else g.unbox(returnType)
        g.returnValue()
        g.endMethod()
    }

    /** `super$name(...)`: invoke the real implementation of the overridden method, skipping the override. */
    private fun generateSuperTrampoline(cw: ClassWriter, m: PeerMethod) {
        val g = GeneratorAdapter(Opcodes.ACC_PUBLIC, AsmMethod(SUPER_PREFIX + m.name, m.descriptor), null, null, cw)
        g.loadThis()
        g.loadArgs()
        g.visitMethodInsn(Opcodes.INVOKESPECIAL, m.ownerInternalName, m.name, m.descriptor, m.ownerIsInterface)
        g.returnValue()
        g.endMethod()
    }

    /** A concrete stub for an abstract supertype method the interpreted class does not override, so the peer is
     *  instantiable and a call reports a clear error. */
    private fun generateAbstractStub(cw: ClassWriter, m: PeerMethod) {
        val g = GeneratorAdapter(Opcodes.ACC_PUBLIC, AsmMethod(m.name, m.descriptor), null, null, cw)
        g.throwException(Type.getType(AbstractMethodError::class.java), "the interpreted class does not override ${m.name}${m.descriptor}")
        g.endMethod()
    }

    private class PeerClassLoader(parent: ClassLoader) : ClassLoader(parent) {
        fun define(name: String, bytes: ByteArray): Class<*> = defineClass(name, bytes, 0, bytes.size)
    }

    private companion object {
        val EMPTY_ARGS = arrayOfNulls<Any?>(0)
        const val VM_FIELD = "vm"
        const val DISPATCH_FIELD = "dispatch"
        const val SUPER_PREFIX = "super$"
        val OBJECT: Type = Type.getType(Any::class.java)
        val DISPATCH: Type = Type.getType(PeerDispatch::class.java)
        val INVOKE = AsmMethod(
            "invoke",
            "(${OBJECT.descriptor}${OBJECT.descriptor}${Type.getType(String::class.java).descriptor}${Type.getType(String::class.java).descriptor}[${OBJECT.descriptor})${OBJECT.descriptor}",
        )
    }
}
