package com.tyron.builder.api.initialization.resolve;

import com.tyron.builder.api.Action;
import com.tyron.builder.api.Incubating;
import com.tyron.builder.api.artifacts.dsl.ComponentMetadataHandler;
import com.tyron.builder.api.artifacts.dsl.RepositoryHandler;
import com.tyron.builder.api.provider.Property;
import com.tyron.builder.internal.HasInternalProtocol;

/**
 * Allows configuring dependency resolution for all projects of the build.
 *
 * @since 6.8
 *
 */
@Incubating
@HasInternalProtocol
public interface DependencyResolutionManagement {
    /**
     * Configures the repositories used by all projects
     * @param repositoryConfiguration the repositories configuration
     */
    void repositories(Action<? super RepositoryHandler> repositoryConfiguration);

    /**
     * Returns the shared repository handler
     */
    RepositoryHandler getRepositories();

    Property<RepositoriesMode> getRepositoriesMode();

    /**
     * Registers component metadata rules used by all projects
     * @param registration the registration action
     */
    void components(Action<? super ComponentMetadataHandler> registration);

    Property<RulesMode> getRulesMode();

    /**
     * Returns the shared component metadata handler
     */
    ComponentMetadataHandler getComponents();

    /**
     * Configures the version catalogs which will be used to generate type safe accessors for dependencies.
     * @param spec the spec to configure the dependencies
     *
     * @since 7.0
     */
    void versionCatalogs(Action<? super MutableVersionCatalogContainer> spec);

    /**
     * Returns the configurable version catalogs.
     *
     * @since 7.0
     */
    MutableVersionCatalogContainer getVersionCatalogs();

    /**
     * Returns the name of the extension generated for type-safe project accessors.
     * Defaults to "projects"
     *
     * @since 7.0
     */
    Property<String> getDefaultProjectsExtensionName();

    /**
     * Returns the name of the extension generated by default from the TOML dependencies
     * file if found. Defaults to "libs".
     *
     * @since 7.0
     */
    Property<String> getDefaultLibrariesExtensionName();
}
