package com.tyron.code.compiler.symbol;

import com.google.common.base.Preconditions;
import com.google.common.collect.ArrayListMultimap;
import com.google.common.collect.Multimap;
import com.tyron.code.compiler.AAPT2Compiler;
import com.tyron.code.model.Project;
import com.tyron.code.service.ILogger;

import java.io.File;
import java.io.IOException;
import java.util.Collection;

/**
 * Class that loads R.txt files generated by AAPT/AAPT2  and converts them
 * to R.java class files
 */
public class SymbolProcessor {

    private final File mSymbolOutputDir;
    private final File mFullResourceFile;
    private final Project mProject;
    private final ILogger mLogger;

    public SymbolProcessor(Project project, ILogger logger) {
        mProject = project;
        mLogger = logger;
        mSymbolOutputDir = new File(project.getBuildDirectory(), "gen");
        mFullResourceFile = new File(project.getBuildDirectory(), "bin/res/R.txt");
    }

    public void run() throws IOException {
        
        SymbolLoader fullSymbolValues = null;
        Multimap<String, SymbolLoader> libMap = ArrayListMultimap.create();

        for (File library : mProject.getLibraries()) {
            File parent = library.getParentFile();
            Preconditions.checkNotNull(parent, "Unable to access parent directory for " + library);

            String packageName = AAPT2Compiler.getPackageName(parent);
            if (packageName == null) {
                continue;
            }

            if (packageName.equals(mProject.getPackageName())) {
                // only generate libraries
                continue;
            }

            File rFile = new File(parent, "R.txt");
            if (!rFile.exists()) {
                continue;
            }

            if (fullSymbolValues == null) {
                fullSymbolValues = new SymbolLoader(mFullResourceFile, mLogger);
                fullSymbolValues.load();
            }
            SymbolLoader libSymbols = new SymbolLoader(rFile, mLogger);
            libSymbols.load();

            libMap.put(packageName, libSymbols);
        }

        // now loop on all the package name, merge all the symbols to write, and write them
        for (String packageName : libMap.keySet()) {
            Collection<SymbolLoader> symbols = libMap.get(packageName);

            SymbolWriter writer = new SymbolWriter(mSymbolOutputDir.getAbsolutePath(), packageName,
                    fullSymbolValues);
            for (SymbolLoader loader : symbols) {
                writer.addSymbolsToWrite(loader);
            }
            writer.write();
        }
    }
}
