version = 2

[module]
type = "java-lib"
name = "lang-java"
languageLevel = "JAVA_17"
output = "build/codeassist/classes"

[sourceSets.main]
scope = "IMPLEMENTATION"
java = ["src/main/kotlin"]

[sourceSets.test]
scope = "TEST_IMPLEMENTATION"
java = ["src/test/kotlin"]

[dependencies]
api = [{ module = "language-api" }]
implementation = [{ module = "index-api" }, { module = "analysis-api" }, { module = "kotlin-compiler-deps" }, { module = "intellij-psi-host" }, "org.ow2.asm:asm:9.7", "kotlin-stdlib"]
testImplementation = [{ platform = "org.junit:junit-bom:5.11.4" }, "org.jetbrains.kotlin:kotlin-test:2.4.0", { module = "test-support" }, { module = "project-model-impl" }, { module = "index-impl" }, "org.jetbrains.kotlinx:kotlinx-coroutines-test:1.11.0"]
