#!/usr/bin/env python3
"""Generates SkiaCalls.kt: one typed C call per distinct ABI shape of skiko's native methods.

Kotlin/Native calls a C function pointer only through a statically typed CFunction, so every
signature the VM may need to call must exist in source. The set is small and fixed by skiko's C
bridges, not by any library above them: 'J' is a 64-bit integer or pointer (a NativePointer, a
long, or any reference argument after marshalling), 'I' a 32-bit int or narrower (bool, byte,
short, char), 'F' a float, 'D' a double.

    python3 tools/skia_call_shapes.py <skiko-awt.jar> > src/iosMain/kotlin/dev/ide/vm/skiko/SkiaCalls.kt
"""
import re, struct, sys, zipfile

def natives(jar):
    out = []
    z = zipfile.ZipFile(jar)
    for n in z.namelist():
        if not n.endswith('.class'): continue
        b = z.read(n)
        off = 10; cnt = struct.unpack('>H', b[8:10])[0]; cp = [None] * cnt; i = 1
        while i < cnt:
            t = b[off]
            if t == 1:
                l = struct.unpack('>H', b[off+1:off+3])[0]; cp[i] = b[off+3:off+3+l].decode('utf8', 'replace'); off += 3 + l
            elif t in (3, 4): off += 5
            elif t in (5, 6): off += 9; i += 1
            elif t in (7, 8, 16, 19, 20): off += 3
            elif t in (9, 10, 11, 12, 17, 18): off += 5
            elif t == 15: off += 4
            i += 1
        off += 6
        ic = struct.unpack('>H', b[off:off+2])[0]; off += 2 + 2 * ic
        for kind in range(2):
            c = struct.unpack('>H', b[off:off+2])[0]; off += 2
            for _ in range(c):
                af, ni, di, ac = struct.unpack('>HHHH', b[off:off+8]); off += 8
                if kind == 1 and af & 0x0100: out.append((cp[ni], cp[di], bool(af & 0x0008)))
                for _ in range(ac):
                    l = struct.unpack('>I', b[off+2:off+6])[0]; off += 6 + l
    return out

def abi(d):
    if d in ('I', 'Z', 'B', 'S', 'C'): return 'I'
    if d == 'F': return 'F'
    if d == 'D': return 'D'
    return 'J'

def ret(d):
    return 'V' if d == 'V' else abi(d)

KT = {'I': 'Int', 'J': 'Long', 'F': 'Float', 'D': 'Double', 'V': 'Unit'}
ARG = {'I': 'a[{0}].toInt()', 'J': 'a[{0}]', 'F': 'Float.fromBits(a[{0}].toInt())', 'D': 'Double.fromBits(a[{0}])'}
RES = {'V': '', 'I': '.toLong()', 'J': '', 'F': '.toRawBits().toLong()', 'D': '.toRawBits()'}

shapes = set()
for name, desc, static in natives(sys.argv[1]):
    params = re.findall(r'\[*(?:L[^;]+;|[ZBCSIJFD])', desc[1:desc.index(')')])
    shape = ''.join(abi(p) for p in params)
    if not static: shape = 'J' + shape  # an instance native's receiver is not passed to C; kept for the count only
    shapes.add(''.join(abi(p) for p in params) + '>' + ret(desc[desc.index(')') + 1:]))
shapes = sorted(shapes)

print('// Generated by run/jvm-vm/tools/skia_call_shapes.py from skiko-awt\'s native method descriptors.')
print('// Regenerate after a skiko upgrade; a shape missing here is reported as unsupported at bind time.')
print('@file:OptIn(kotlinx.cinterop.ExperimentalForeignApi::class)')
print()
print('package dev.ide.vm.skiko')
print()
print('import kotlinx.cinterop.CFunction')
print('import kotlinx.cinterop.COpaquePointer')
print('import kotlinx.cinterop.invoke')
print('import kotlinx.cinterop.reinterpret')
print()
print('/** Shape key (`JFF>V`: parameters, then the return) to the index [callSkia] dispatches on. */')
print('internal val skiaShapes: Map<String, Int> = mapOf(')
for k, s in enumerate(shapes): print(f'    "{s}" to {k},')
print(')')
print()
print('/** Calls [fn] as shape [shape] with [a] (each argument\'s raw bits) and returns the result\'s raw bits. */')
print('internal fun callSkia(shape: Int, fn: COpaquePointer, a: LongArray): Long = when (shape) {')
for k, s in enumerate(shapes):
    p, r = s.split('>')
    sig = '(' + ', '.join(KT[c] for c in p) + ') -> ' + KT[r]
    args = ', '.join(ARG[c].format(i) for i, c in enumerate(p))
    call = f'fn.reinterpret<CFunction<{sig}>>()({args})'
    print(f'    {k} -> {{ {call}; 0L }}' if r == 'V' else f'    {k} -> {call}{RES[r]}')
print('    else -> error("unknown skia call shape $shape")')
print('}')
