#!/usr/bin/env python3
"""Generates skikoBridges.def: a cinterop table of every C bridge skiko's iOS build exports.

The VM calls skia through skiko's C bridges by name. Referencing each of them from this table is what
makes the linker keep them (nothing else in the binary calls most of them), and the table is how the VM
finds them: skikoBridgeLookup(name) -> function pointer, with no dlsym and no exported symbols.

    python3 tools/skiko_bridges_def.py <skiko-iossimulatorarm64.klib> > src/nativeInterop/cinterop/skikoBridges.def
"""
import subprocess, sys, tempfile, zipfile, os

klib = sys.argv[1]
with tempfile.TemporaryDirectory() as d:
    zipfile.ZipFile(klib).extractall(d)
    archives = []
    for root, _, files in os.walk(d):
        archives += [os.path.join(root, f) for f in files if f.startswith('skiko-native-bridges') and f.endswith('.a')]
    syms = set()
    for a in archives:
        out = subprocess.run(['nm', '-gU', a], capture_output=True, text=True).stdout
        for line in out.splitlines():
            parts = line.split()
            if len(parts) == 3 and parts[1] == 'T' and parts[2].startswith('_org_jetbrains_'):
                syms.add(parts[2][1:])
syms = sorted(syms)

print('# Generated by run/jvm-vm/tools/skiko_bridges_def.py from skiko\'s iOS klib. Regenerate after a skiko')
print('# upgrade: a bridge removed upstream fails the link, one added is simply not reachable until then.')
print('package = dev.ide.vm.skiko.bridges')
print('---')
print('#include <string.h>')
print()
for s in syms: print(f'extern char {s};')
print()
print('typedef struct { const char* name; void* fn; } SkikoBridge;')
print()
print('static const SkikoBridge skikoBridges[] = {')
for s in syms: print(f'    {{ "{s}", &{s} }},')
print('};')
print()
print('/** The bridge called [name], or NULL. The table is sorted, so this is a binary search. */')
print('static inline void* skikoBridgeLookup(const char* name) {')
print(f'    int lo = 0, hi = {len(syms)} - 1;')
print('    while (lo <= hi) {')
print('        int mid = (lo + hi) / 2;')
print('        int c = strcmp(skikoBridges[mid].name, name);')
print('        if (c == 0) return skikoBridges[mid].fn;')
print('        if (c < 0) lo = mid + 1; else hi = mid - 1;')
print('    }')
print('    return 0;')
print('}')
print()
print(f'static inline int skikoBridgeCount(void) {{ return {len(syms)}; }}')
