package dev.ide.lang.jdt.completion

import dev.ide.lang.jdt.env.JdtEnvironmentCache
import dev.ide.lang.jdt.env.JdtNameEnvironment
import dev.ide.lang.jdt.env.JdtSourceUnit
import org.eclipse.jdt.internal.compiler.Compiler
import org.eclipse.jdt.internal.compiler.DefaultErrorHandlingPolicies
import org.eclipse.jdt.internal.compiler.ICompilerRequestor
import org.eclipse.jdt.core.compiler.IProblem
import org.eclipse.jdt.internal.compiler.ast.CompilationUnitDeclaration
import org.eclipse.jdt.internal.compiler.ast.TypeDeclaration
import org.eclipse.jdt.internal.compiler.impl.CompilerOptions
import org.eclipse.jdt.internal.compiler.lookup.ReferenceBinding
import org.eclipse.jdt.internal.compiler.lookup.SourceTypeBinding
import org.eclipse.jdt.internal.compiler.lookup.TagBits
import org.eclipse.jdt.internal.compiler.problem.DefaultProblemFactory
import java.nio.file.Path
import java.util.Locale

/**
 * Parses + resolves a focal source unit with ecj's internal compiler driven by [JdtNameEnvironment]
 * (project model + in-memory overlay + jars + jrt — no disk flush). The focal unit is excluded from
 * the environment so it is the sole definition of its type. Statement/method recovery is on, so a
 * broken buffer still yields a resolved tree.
 *
 * The keystroke-invariant environment state (jrt index, jar handles, package set) lives in one shared
 * [JdtEnvironmentCache] for the resolver's whole life — a [JdtCompletion] (hence one resolver)
 * exists per analyzer/module. Each resolve wraps that cache in a fresh, cheap [JdtNameEnvironment]
 * carrying only the current editor overlay + the excluded focal type. Building the cache once, rather
 * than per resolve, is what keeps completion off the GC: see [JdtEnvironmentCache].
 */
internal class JdtResolver(
    private val sourceRoots: List<Path>,
    classpathJars: List<Path>,
    jdkHome: Path?,
    private val complianceLevel: Long,
    /** The workspace index, for the name environment's `java.classLocator` fast path (see [JdtEnvironmentCache]). */
    indexProvider: () -> dev.ide.index.IndexService? = { null },
) {
    private val cache = JdtEnvironmentCache(sourceRoots, classpathJars, jdkHome, indexProvider)

    /** Release the shared environment's per-module resources (the open library-jar handles). */
    fun dispose() = cache.dispose()

    /**
     * Resolve the focal unit for its **diagnostics** — the binding-level problems ecj reports — over the
     * shared in-memory environment, with no disk-environment scan and no shadow-file dance (the env excludes
     * the focal type by FQCN, so there is never a duplicate definition). [options] is the host's `JavaCore`
     * compiler-options map, so the warning/error configuration matches the DOM analyzer's exactly — the
     * problem set is the same ecj output, just produced off the cached environment instead of a fresh
     * disk-scanning DOM parse. Statement/method recovery is on so a broken buffer still yields problems.
     */
    fun diagnose(focalFqcn: String, focalText: String, overlay: Map<String, CharArray>, options: Map<String, String>): Array<out IProblem> {
        val env = JdtNameEnvironment(cache, sourceRoots, overlay, setOf(focalFqcn), ownsCache = false)
        val opts = CompilerOptions(options).apply {
            performMethodsFullRecovery = true
            performStatementsRecovery = true
            storeAnnotations = false
        }
        val compiler = Compiler(
            env,
            DefaultErrorHandlingPolicies.proceedWithAllProblems(),
            opts,
            ICompilerRequestor { },
            DefaultProblemFactory(Locale.getDefault()),
        )
        return try {
            // resolve(unit, verifyMethods, analyzeCode, generateCode). generateCode is on for diagnostic
            // PARITY only: in this ecj build the flow-analysis warnings the DOM analyzer reports (unused
            // local, etc.) are emitted during the code-gen pass, not analyseCode — so without it the problem
            // set silently drops them. The generated bytecode goes to a no-op requestor (never written), and
            // ecj skips codegen for units that have errors, so the extra work only touches clean buffers.
            val cud = compiler.resolve(JdtSourceUnit(focalFqcn, focalText.toCharArray()), true, true, true)
            val problems = cud?.compilationResult?.allProblems ?: return emptyArray<IProblem>()
            enrichHierarchyProblems(cud, problems)
        } catch (_: Throwable) {
            emptyArray<IProblem>() // degrade to no diagnostics on pathological input, exactly like resolve()
        }
    }

    /**
     * ecj's "The hierarchy of the type X is inconsistent" ([IProblem.HierarchyHasProblems]) names only the
     * broken subtype — never the ancestor actually missing from the classpath, which is exactly what you need
     * to know which dependency to add. We have the resolved binding tree in hand here, so for each such
     * problem we walk the type's supertype graph for the first unresolvable binding and fold its qualified
     * name (and the supertype that required it) into the message. The problem's source span is the type
     * name's span (ecj reports it at `type.sourceStart()`), so we key the lookup by position — an exact,
     * collision-free match. Best-effort: any binding-walk hiccup leaves the original problem untouched.
     */
    private fun enrichHierarchyProblems(cud: CompilationUnitDeclaration, problems: Array<out IProblem>): Array<out IProblem> {
        if (problems.none { it.id == IProblem.HierarchyHasProblems }) return problems
        val detailByPos = HashMap<Int, String>()
        forEachSourceType(cud.types) { binding ->
            if ((binding.tagBits and TagBits.HierarchyHasProblems) == 0L) return@forEachSourceType
            val missing = LinkedHashMap<String, String>() // missing FQN -> the supertype that required it
            runCatching { collectMissingAncestors(binding, missing, HashSet(), 0) }
            if (missing.isEmpty()) return@forEachSourceType
            val detail = missing.entries.joinToString(", ") { (fqn, via) ->
                if (via.isEmpty() || via == fqn) fqn else "$fqn (required by $via)"
            }
            runCatching { detailByPos[binding.sourceStart()] = detail }
        }
        if (detailByPos.isEmpty()) return problems
        return Array(problems.size) { i ->
            val p = problems[i]
            val detail = if (p.id == IProblem.HierarchyHasProblems) detailByPos[p.sourceStart] else null
            if (detail != null) MessageEnrichedProblem(p, "${p.message} — missing from the classpath: $detail") else p
        }
    }

    /** Visit every source type binding in [types], including nested member types. */
    private fun forEachSourceType(types: Array<TypeDeclaration>?, action: (SourceTypeBinding) -> Unit) {
        types ?: return
        for (t in types) {
            t.binding?.let(action)
            forEachSourceType(t.memberTypes, action)
        }
    }

    /**
     * Walk [type]'s superclass + superinterfaces depth-first, recording each unresolvable (missing) binding
     * keyed by its qualified name → the supertype that referenced it. A valid supertype whose OWN hierarchy is
     * flagged broken is descended into to reach the real missing leaf. The seen-set + depth cap guard cycles.
     */
    private fun collectMissingAncestors(
        type: ReferenceBinding,
        out: MutableMap<String, String>,
        seen: MutableSet<ReferenceBinding>,
        depth: Int,
    ) {
        if (depth > 64 || !seen.add(type)) return
        val supers = ArrayList<ReferenceBinding>(4)
        runCatching { type.superclass()?.let { supers.add(it) } }
        runCatching { type.superInterfaces()?.forEach { if (it != null) supers.add(it) } }
        for (s in supers) {
            if (!s.isValidBinding) {
                out.putIfAbsent(String(s.readableName()), String(type.readableName()))
            } else if ((s.tagBits and TagBits.HierarchyHasProblems) != 0L) {
                collectMissingAncestors(s, out, seen, depth + 1)
            }
        }
    }

    /** An [IProblem] that delegates everything but reports an [enriched] message; see [enrichHierarchyProblems]. */
    private class MessageEnrichedProblem(delegate: IProblem, private val enriched: String) : IProblem by delegate {
        override fun getMessage(): String = enriched
    }

    fun resolve(focalFqcn: String, focalText: String, overlay: Map<String, CharArray>): CompilationUnitDeclaration? {
        val env = JdtNameEnvironment(cache, sourceRoots, overlay, setOf(focalFqcn), ownsCache = false)
        val options = CompilerOptions().apply {
            complianceLevel = this@JdtResolver.complianceLevel
            sourceLevel = this@JdtResolver.complianceLevel
            targetJDK = this@JdtResolver.complianceLevel
            performMethodsFullRecovery = true
            performStatementsRecovery = true
            storeAnnotations = false
        }
        val compiler = Compiler(
            env,
            DefaultErrorHandlingPolicies.proceedWithAllProblems(),
            options,
            ICompilerRequestor { },
            DefaultProblemFactory(Locale.getDefault()),
        )
        return try {
            compiler.resolve(JdtSourceUnit(focalFqcn, focalText.toCharArray()), true, true, false)
        } catch (_: Throwable) {
            null // resolution can throw on pathological input; degrade to no completion
        } finally {
            env.cleanup()
        }
    }
}
