version = 2

[module]
type = "java-lib"
name = "decompiler"
languageLevel = "JAVA_17"
output = "build/codeassist/classes"

[sourceSets.main]
scope = "IMPLEMENTATION"
java = ["src/main/kotlin"]

[sourceSets.test]
scope = "TEST_IMPLEMENTATION"
java = ["src/test/kotlin"]

[dependencies]
api = [{ module = "language-api" }]
implementation = [{ module = "lang-kotlin-index" }, "org.benf:cfr:0.152", "org.ow2.asm:asm:9.7", "org.jetbrains.kotlin:kotlin-metadata-jvm:2.4.0", "kotlin-stdlib"]
testImplementation = [{ platform = "org.junit:junit-bom:5.11.4" }, "org.jetbrains.kotlin:kotlin-test:2.4.0", { module = "test-support" }]
